/**
 * One true cryptic clue per answer word: a definition at one end plus
 * wordplay that builds the answer another way. `how` is the parse — shown
 * on the results card after a cryptic day, and what a reviewer checks.
 *
 * No ANAGRAM cryptics: the letter pad already shows the six letters, so
 * "shuffled" wordplay would hand the answer over. The toolkit is charades
 * (A + B), containers, hidden words, sound-alikes, deletions and — where a
 * word resists — an honest double definition.
 *
 * Conventional abbreviations: ED editor, ER hesitation, RS Royal Society,
 * EL elevated railway, S son, T time, D died, R right, C about, RE on/about,
 * EST establishment, OR gold, CE Church of England, CH church, ST street;
 * DE/LE/LES/UN/ET/FIN/MER are French, ES/SI Spanish, DER German.
 *
 * AI-written, then two AI editor passes (every charade and hidden word
 * checked against its answer mechanically). A human read is still owed.
 */
export interface Cryptic {
  clue: string;
  how: string;
}

export const CRYPTIC: Readonly<Record<string, Cryptic>> = {
  angels: { clue: "Heavenly hosts backing startups", how: "Double definition" },
  angles: { clue: "Fishes for viewpoints", how: "Double definition: angles (fishes) / angles (viewpoints)" },
  begins: { clue: "Starts to exist with spirit and son", how: "BE (exist) + GIN (spirit) + S (son)" },
  beings: { clue: "Creatures exist at home with good son", how: "BE (exist) + IN (at home) + G (good) + S (son)" },
  brakes: { clue: "Stoppers from British garden tools", how: "B (British) + RAKES" },
  breaks: { clue: "Fractures or lucky chances", how: "Double definition" },
  burden: { clue: "Load: prickly seed head beside lair", how: "BUR (prickly seed head) + DEN (lair)" },
  burned: { clue: "Scorched some Auburn edifices", how: "Hidden in auBURN EDifices" },
  caring: { clue: "Kind vehicle with ring beheaded", how: "CAR (vehicle) + (r)ING (ring, beheaded)" },
  racing: { clue: "Sport of kings, pounding", how: "Double definition" },
  course: { clue: "Dish: swear word holding a ring", how: "CURSE (swear word) holding O (ring)" },
  source: { clue: "Origin found in sour cereal", how: "Hidden in SOUR CEreal" },
  credit: { clue: "Recognition: cold, right, then revise", how: "C (cold) + R (right) + EDIT (revise)" },
  direct: { clue: "Straight, dreadful, then Connecticut", how: "DIRE + CT (Connecticut)" },
  danger: { clue: "Peril is daughter's rage", how: "D (daughter) + ANGER" },
  garden: { clue: "Fish before lair, where roses grow", how: "GAR (fish) + DEN (lair)" },
  denial: { clue: "Refusal in Camden, I allege", how: "Hidden in (Cam)DEN I AL(lege)" },
  nailed: { clue: "Aced: new, felt poorly", how: "N (new) + AILED (felt poorly)" },
  depart: { clue: "Leave \"of,\" in Paris, a role", how: "DE (French \"of\") + PART (role)" },
  parted: { clue: "Separated: role, then editor", how: "PART (role) + ED (editor)" },
  design: { clue: "Plan of, in Paris, an omen", how: "DE (French \"of\") + SIGN (omen)" },
  signed: { clue: "Autographed notice for the editor", how: "SIGN (notice) + ED (editor)" },
  duties: { clue: "Tasks: \"of the,\" in Paris, draws", how: "DU (French \"of the\") + TIES (draws)" },
  suited: { clue: "Matched: hotel room, daughter", how: "SUITE (hotel room) + D (daughter)" },
  equals: { clue: "Peers even with son", how: "EQUAL (even) + S (son)" },
  squeal: { clue: "Rat, or a pig's cry", how: "Double definition" },
  escort: { clue: "Usher, key and scrap", how: "ESC (escape key) + ORT (scrap)" },
  sector: { clue: "Zone: cult with gold", how: "SECT (cult) + OR (gold)" },
  forest: { clue: "Woods supporting established", how: "FOR (supporting) + EST (established)" },
  foster: { clue: "Promote actress Jodie", how: "Double definition (promote / Jodie FOSTER)" },
  groans: { clue: "Moans: good horses", how: "G (good) + ROANS (horses)" },
  organs: { clue: "Kidneys, say: instrument and son", how: "ORGAN + S (son)" },
  hatred: { clue: "Loathing: cap, communist", how: "HAT + RED (communist)" },
  thread: { clue: "Strand: \"the,\" cut short, then study", how: "TH(e) + READ (study)" },
  hostel: { clue: "Budget inn: emcee, elevated train", how: "HOST (emcee) + EL (elevated train)" },
  hotels: { clue: "Inns: spicy elevated trains", how: "HOT (spicy) + ELS (elevated railways)" },
  ideals: { clue: "Standards: one with bargains", how: "I (one) + DEALS (bargains)" },
  ladies: { clue: "Women: L.A. expires", how: "LA + DIES" },
  sailed: { clue: "Went by boat: son was ill", how: "S (son) + AILED (was ill)" },
  ignore: { clue: "Snub in big no-reply, partly", how: "Hidden: bIG NO REply" },
  region: { clue: "Area about soldier on", how: "RE (about) + GI (soldier) + ON" },
  insect: { clue: "Bug at home with a cult", how: "IN (at home) + SECT (cult)" },
  nicest: { clue: "Kindest French city, street", how: "NICE + ST (street)" },
  antler: { clue: "Stag's horn: worker, left, then hesitation", how: "ANT (worker) + L (left) + ER (hesitation)" },
  rental: { clue: "Leased place: tear with aluminum", how: "RENT (tear) + AL (aluminum)" },
  lights: { clue: "Lamps: not heavy, son", how: "LIGHT (not heavy) + S (son)" },
  slight: { clue: "Snub: small lamp", how: "S (small) + LIGHT (lamp)" },
  listen: { clue: "Hear: register, then printer's space", how: "LIST (register) + EN (printer's space)" },
  silent: { clue: "Mum: yes in Spain, loaned", how: "SI (Spanish \"yes\") + LENT (loaned)" },
  lowest: { clue: "Bottom: moo, established", how: "LOW (moo) + EST (established)" },
  towels: { clue: "Dryers pull elevated trains", how: "TOW (pull) + ELS (elevated railways)" },
  marine: { clue: "Of the sea, or a leatherneck", how: "Double definition" },
  remain: { clue: "Stay on the sea", how: "RE (on) + MAIN (the sea)" },
  master: { clue: "Expert: pole, then hesitation", how: "MAST (pole) + ER (hesitation)" },
  stream: { clue: "Brook: street with paper", how: "ST (street) + REAM (paper)" },
  models: { clue: "Poses: fashion, left, son", how: "MODE (fashion) + L (left) + S (son)" },
  seldom: { clue: "Rarely found in diesel domestic cars", how: "Hidden in dieSEL DOMestic" },
  nights: { clue: "Evenings: chessmen losing king", how: "(k)NIGHTS, minus K (king)" },
  things: { clue: "Objects: whatsit and son", how: "THING (whatsit) + S (son)" },
  patrol: { clue: "Beat: tap, then roll cut short", how: "PAT (tap) + ROL(l)" },
  portal: { clue: "Entrance: harbor, then aluminum", how: "PORT (harbor) + AL (aluminum)" },
  pilots: { clue: "Flyers: Greek letter, plenty", how: "PI (Greek letter) + LOTS (plenty)" },
  pistol: { clue: "Gun in tulip is tolerant", how: "Hidden: tuliP IS TOLerant" },
  plains: { clue: "Prairies: simple son", how: "PLAIN (simple) + S (son)" },
  spinal: { clue: "Of the backbone: turn, then aluminum", how: "SPIN (turn) + AL (aluminum)" },
  ransom: { clue: "Release price found in veteran sommelier", how: "Hidden in veteRAN SOMmelier" },
  romans: { clue: "Caesar's people: French novel, son", how: "ROMAN (French \"novel\") + S (son)" },
  resign: { clue: "Quit about a notice", how: "RE (about) + SIGN (notice)" },
  singer: { clue: "Vocalist: croon, hesitation", how: "SING (croon) + ER (hesitation)" },
  sacred: { clue: "Holy: pouch, then crimson", how: "SAC (pouch) + RED (crimson)" },
  scared: { clue: "Frightened: son minded", how: "S (son) + CARED (minded)" },
  spared: { clue: "Let off: resort, communist", how: "SPA (resort) + RED (communist)" },
  spread: { clue: "Lavish meal on a ranch", how: "Double definition: spread (lavish meal) / spread (ranch)" },
  stable: { clue: "Steady small piece of furniture", how: "S (small) + TABLE (furniture)" },
  tables: { clue: "Charts: bill with \"the,\" in Paris", how: "TAB (bill) + LES (French \"the\")" },
  stayed: { clue: "Remained: street, yes vote, died", how: "ST (street) + AYE (yes vote) + D (died)" },
  steady: { clue: "Firm place, unknown", how: "STEAD (place) + Y (unknown)" },
  strain: { clue: "Tax son's line of railroad cars", how: "S (son's) + TRAIN (line of railroad cars)" },
  trains: { clue: "Coaches: time and showers", how: "T (time) + RAINS (showers)" },
  struck: { clue: "Hit small rig", how: "S (small) + TRUCK (rig)" },
  trucks: { clue: "Rigs hidden in that rucksack", how: "Hidden in thaT RUCKSack" },
  wander: { clue: "Roam: magic stick, hesitation", how: "WAND + ER (hesitation)" },
  warden: { clue: "Keeper of conflict den", how: "WAR (conflict) + DEN" },
  warned: { clue: "Cautioned: battle with Ned", how: "WAR (battle) + NED" },
  actors: { clue: "Players found in fact or superstition", how: "Hidden in f(ACT OR S)uperstition" },
  costar: { clue: "Fellow lead: price, then Arkansas", how: "COST (price) + AR (Arkansas)" },
  castor: { clue: "Gemini star: throw gold", how: "CAST (throw) + OR (gold)" },
  aliens: { clue: "Outsiders: one with property claims", how: "A (one) + LIENS (property claims)" },
  saline: { clue: "Salty: South Africa's line", how: "SA (South Africa) + LINE" },
  ashore: { clue: "On land: a coast", how: "A + SHORE (coast)" },
  hoarse: { clue: "Croaky mount, we hear", how: "Sounds like HORSE (mount)" },
  badger: { clue: "Pester: evil German", how: "BAD (evil) + GER (German)" },
  barged: { clue: "Pushed in: boat, then daughter", how: "BARGE (boat) + D (daughter)" },
  barely: { clue: "Only just: bachelor, a, trust", how: "B (bachelor) + A + RELY (trust)" },
  barley: { clue: "Grain: bachelor on headless Harley", how: "B (bachelor) + (h)ARLEY (Harley, headless)" },
  bleary: { clue: "Dim-eyed: book, Shakespeare king, day's end", how: "B (book) + LEAR (Shakespeare king) + Y (day's end)" },
  blamed: { clue: "Faulted: bachelor, feeble, then died", how: "B (bachelor) + LAME (feeble) + D (died)" },
  bedlam: { clue: "Chaos: bed, then lamb cut short", how: "BED + LAM(b) (lamb, cut short)" },
  boiler: { clue: "Heater: seethe, hesitation", how: "BOIL (seethe) + ER (hesitation)" },
  reboil: { clue: "Heat again, regarding bubble", how: "RE (regarding) + BOIL (bubble)" },
  breast: { clue: "Chest in timbre astounds", how: "Hidden: timBRE ASTounds" },
  barest: { clue: "Most minimal: pub, Eastern time", how: "BAR (pub) + EST (Eastern Standard Time)" },
  breath: { clue: "Air: British garland, beheaded", how: "B (British) + (w)REATH (garland)" },
  bather: { clue: "Swimmer: tub, hesitation", how: "BATH (tub) + ER (hesitation)" },
  bridal: { clue: "Of a wedding, horse's headgear, we hear", how: "Sounds like BRIDLE" },
  ribald: { clue: "Racy: Rhode Island, hairless", how: "RI (Rhode Island) + BALD (hairless)" },
  bruise: { clue: "Mark: British trick, one inside", how: "B (British) + RU(I)SE (trick holding one)" },
  buries: { clue: "Inters fruits, we hear", how: "Sounds like BERRIES" },
  busier: { clue: "More hectic coach at pier, headless", how: "BUS (coach) + (p)IER" },
  rubies: { clue: "Gems in cherub I estimate", how: "Hidden: cheRUB I EStimate" },
  busted: { clue: "Caught: sculpture, editor", how: "BUST (sculpture) + ED (editor)" },
  debuts: { clue: "Premieres: \"of,\" in Paris, objections", how: "DE (French \"of\") + BUTS (objections)" },
  buster: { clue: "Pal: raid, then hesitation", how: "BUST (raid) + ER (hesitation)" },
  brutes: { clue: "Thugs: dry wine is, in Madrid", how: "BRUT (dry wine) + ES (Spanish \"is\")" },
  tubers: { clue: "Potatoes: TV, right, son", how: "TUBE (TV, as in \"the tube\") + R (right) + S (son)" },
  rebuts: { clue: "Counters about objections", how: "RE (about) + BUTS (objections)" },
  candle: { clue: "Light: tin, daughter, \"the\" in Paris", how: "CAN (tin) + D (daughter) + LE (French \"the\")" },
  lanced: { clue: "Pierced: spear, five hundred", how: "LANCE (spear) + D (five hundred, Roman numeral)" },
  cartel: { clue: "Ring: wagon on elevated railway", how: "CART (wagon) + EL (elevated railway)" },
  claret: { clue: "Wine: Irish county, time", how: "CLARE (Irish county) + T (time)" },
  castle: { clue: "Rook: throw \"the,\" in Paris", how: "CAST (throw) + LE (French \"the\")" },
  cleats: { clue: "Shoes found in uncle at sea", how: "Hidden: unCLE AT Sea" },
  chains: { clue: "Links: church, a trendy son", how: "CH (church) + A + IN (trendy) + S (son)" },
  chinas: { clue: "Porcelain sets: jaw, while", how: "CHIN (jaw) + AS (while)" },
  charts: { clue: "Graphs: about deer", how: "C (about) + HARTS (deer)" },
  starch: { clue: "Stiffener: celebrity church", how: "STAR (celebrity) + CH (church)" },
  cinema: { clue: "Movie house in vaccine maker", how: "Hidden in vacCINE MAker" },
  anemic: { clue: "Weak: a northeast microphone", how: "A + NE (northeast) + MIC (microphone)" },
  iceman: { clue: "Cool one: diamonds, fellow", how: "ICE (diamonds) + MAN (fellow)" },
  clears: { clue: "Removes some nuclear science", how: "Hidden in nuCLEAR Science" },
  scaler: { clue: "Climber: flake, right", how: "SCALE (flake) + R (right)" },
  cursed: { clue: "Swore: mutts, editor", how: "CURS (mutts) + ED (editor)" },
  crudes: { clue: "Oils: muck is, in Madrid", how: "CRUD (muck) + ES (Spanish \"is\")" },
  dancer: { clue: "Hoofer: ball, right", how: "DANCE (ball) + R (right)" },
  craned: { clue: "Stretched: bird, died", how: "CRANE (bird) + D (died)" },
  dances: { clue: "Proms: ball and son", how: "DANCE (ball) + S (son)" },
  ascend: { clue: "Climb: a dispatch holding \"about\"", how: "A + S(C)END (send holding C, about)" },
  deacon: { clue: "Church officer: drug agency, trick", how: "DEA (drug agency) + CON (trick)" },
  canoed: { clue: "Paddled: small boat, then Democrat", how: "CANOE (small boat) + D (Democrat)" },
  debris: { clue: "Rubble: debutante, Rhode Island, son", how: "DEB + RI (Rhode Island) + S (son)" },
  brides: { clue: "Veil wearers: British trips", how: "B (British) + RIDES (trips)" },
  detail: { clue: "Fine point: \"of,\" in Paris, end", how: "DE (French \"of\") + TAIL (end)" },
  dilate: { clue: "Widen: cube holding back muscle", how: "DIE (cube) around LAT (back muscle)" },
  tailed: { clue: "Shadowed: time, felt ill", how: "T (time) + AILED (felt ill)" },
  detour: { clue: "Bypass made tourists late, in part", how: "Hidden in maDE TOURists" },
  routed: { clue: "Crushed: defeat for the editor", how: "ROUT (defeat) + ED (editor)" },
  toured: { clue: "Went on the road: trip, editor", how: "TOUR (trip) + ED (editor)" },
  diaper: { clue: "Baby wear seen in India persistently", how: "Hidden in (In)DIA PER(sistently)" },
  paired: { clue: "Matched: quietly broadcast", how: "P (quiet, piano) + AIRED (broadcast)" },
  repaid: { clue: "Paid back salesman's help", how: "REP (salesman) + AID (help)" },
  donate: { clue: "Give: put on, dined", how: "DON (put on) + ATE (dined)" },
  atoned: { clue: "Made amends: a fit", how: "A + TONED (fit)" },
  drives: { clue: "Motivations: doctor and composer", how: "DR (doctor) + IVES (Charles Ives)" },
  divers: { clue: "Scuba fans: plunge, right, son", how: "DIVE (plunge) + R (right) + S (son)" },
  drones: { clue: "Male bees: doctor's singles", how: "DR (doctor) + ONES (singles)" },
  snored: { clue: "Slept noisily, son saying no to Red", how: "S (son) + NO (saying no) + RED" },
  editor: { clue: "Newspaper boss seen in credit order", how: "Hidden in crEDIT ORder" },
  rioted: { clue: "Ran amok: uproar, energy, daughter", how: "RIOT (uproar) + E (energy) + D (daughter)" },
  triode: { clue: "Tube: three, poem", how: "TRI (three) + ODE (poem)" },
  failed: { clue: "Flunked: female was sick", how: "F (female) + AILED (was sick)" },
  afield: { clue: "Far away: a meadow", how: "A + FIELD (meadow)" },
  faster: { clue: "Quicker abstainer", how: "Double definition: quicker / one who fasts" },
  strafe: { clue: "Rake with fire, or sidestep shooting", how: "Double definition" },
  filter: { clue: "Strainer, or a photo effect", how: "Double definition" },
  lifter: { clue: "Weight trainer: raise, hesitation", how: "LIFT (raise) + ER (hesitation)" },
  trifle: { clue: "Small matter: time for a gun", how: "T (time) + RIFLE (gun)" },
  finest: { clue: "Best: \"end,\" in Paris, established", how: "FIN (French \"end\") + EST (established)" },
  infest: { clue: "Overrun: at home with a festival", how: "IN (at home) + FEST (festival)" },
  finger: { clue: "Digit: \"end,\" in Paris, German", how: "FIN (French \"end\") + GER (German)" },
  fringe: { clue: "Edge: loud call, energy", how: "F (loud) + RING (call) + E (energy)" },
  forces: { clue: "Compels: loud monster is, in Madrid", how: "F (loud) + ORC (monster) + ES (Spanish \"is\")" },
  fresco: { clue: "Mural: new, not hot, company", how: "FRES(h) (new, minus H for hot) + CO (company)" },
  formed: { clue: "Shaped tax document for editor", how: "FORM (tax document) + ED (editor)" },
  deform: { clue: "Warp found in homemade formula", how: "Hidden in homemaDE FORMula" },
  freaks: { clue: "Oddballs panic", how: "Double definition: freaks (oddballs) / freaks (panics, informal)" },
  fakers: { clue: "Phonies in sofa Kershaw bought", how: "Hidden in (so)FA KERS(haw)" },
  friend: { clue: "Pal: Friday, then finish", how: "FRI (Friday) + END (finish)" },
  finder: { clue: "Locator: fish part, then German 'the'", how: "FIN (fish part) + DER (German \"the\")" },
  gifted: { clue: "Talented: present for the editor", how: "GIFT (present) + ED (editor)" },
  fidget: { clue: "Squirm: Fido docked, then obtain", how: "FID(o) (Fido, tail docked) + GET (obtain)" },
  golden: { clue: "Gilded in big olden days", how: "Hidden: biG OLDEN days" },
  longed: { clue: "Pined: tall, editor", how: "LONG (tall) + ED (editor)" },
  grapes: { clue: "Vine fruit: Greek mimics", how: "GR (Greek) + APES (mimics)" },
  pagers: { clue: "Beepers seen in page RSVPs", how: "Hidden in (PAGE RS)VPs" },
  grunts: { clue: "Foot soldiers: good weaklings", how: "G (good) + RUNTS (weaklings)" },
  strung: { clue: "Threaded: street step", how: "ST (street) + RUNG (step)" },
  hearts: { clue: "Suit: he, crafts", how: "HE + ARTS (crafts)" },
  earths: { clue: "Soils: fireplaces losing hot", how: "(h)EARTHS, minus H (hot)" },
  haters: { clue: "Critics in that ersatz coffee", how: "Hidden in (t)HAT ERS(atz)" },
  hustle: { clue: "Hurry, or a con", how: "Double definition" },
  sleuth: { clue: "Private eye, or to track", how: "Double definition" },
  images: { clue: "Pictures: one with wizards", how: "I (one) + MAGES (wizards)" },
  ageism: { clue: "Bias in sage is modest", how: "Hidden in (s)AGE IS M(odest)" },
  inches: { clue: "Creeps: home, then chest cut short", how: "IN (home) + CHES(t)" },
  niches: { clue: "Nooks found in Munich estates", how: "Hidden: muNICH ESTates" },
  insult: { clue: "Offend some in sultry weather", how: "Hidden in IN SULTry" },
  sunlit: { clue: "Bright: star, burning", how: "SUN (star) + LIT (burning)" },
  itself: { clue: "By ___: tech support, ego", how: "IT (tech support) + SELF (ego)" },
  stifle: { clue: "Smother some beast, if left", how: "Hidden in beaST IF LEft" },
  filets: { clue: "Cuts: loud one allows", how: "F (loud) + I (one) + LETS (allows)" },
  lasted: { clue: "Endured in Dallas, tediously", how: "Hidden in (Dal)LAS TED(iously)" },
  deltas: { clue: "River mouths: shoulder muscle, like", how: "DELT (shoulder muscle) + AS (like)" },
  layers: { clue: "Tiers: song, hesitations", how: "LAY (song) + ERS (hesitations)" },
  relays: { clue: "Passes on about songs", how: "RE (about) + LAYS (songs)" },
  slayer: { clue: "Killer: son, hen", how: "S (son) + LAYER (hen)" },
  layout: { clue: "Design: song, away", how: "LAY (song) + OUT (away)" },
  outlay: { clue: "Spending: absent ballad", how: "OUT (absent) + LAY (ballad)" },
  linked: { clue: "Joined: left, tattooed", how: "L (left) + INKED (tattooed)" },
  kindle: { clue: "Ignite nice \"the,\" in Paris", how: "KIND (nice) + LE (French \"the\")" },
  listed: { clue: "Itemized: register for editor", how: "LIST (register) + ED (editor)" },
  delist: { clue: "Remove \"of\" catalog, in Paris", how: "DE (French \"of\") + LIST (catalog)" },
  locker: { clue: "Storage: bolt, hesitation", how: "LOCK (bolt) + ER (hesitation)" },
  relock: { clue: "Bolt again about a tress", how: "RE (about) + LOCK (tress)" },
  lovers: { clue: "Sweethearts: zero, right, son", how: "LOVE (zero) + R (right) + S (son)" },
  solver: { clue: "Puzzle whiz: sun in Spain, very, hesitation", how: "SOL (Spanish \"sun\") + V (very) + ER (hesitation)" },
  maiden: { clue: "First: mother, one, study", how: "MA (mother) + I (one) + DEN (study)" },
  median: { clue: "Middle: press, new", how: "MEDIA (press) + N (new)" },
  marble: { clue: "Stone: spoil, capable minus A", how: "MAR (spoil) + (a)BLE" },
  ramble: { clue: "Wander: right stroll", how: "R (right) + AMBLE (stroll)" },
  medals: { clue: "Honors in famed Alsace wines", how: "Hidden in fa(MED ALS)ace" },
  damsel: { clue: "Maiden: mothers, railway", how: "DAMS (mothers) + EL (elevated railway)" },
  mental: { clue: "Of the mind: guys, tall, cut short", how: "MEN (guys) + TAL(l)" },
  lament: { clue: "Mourn: weak New Testament", how: "LAME (weak) + NT (New Testament)" },
  mantle: { clue: "Cloak, or the earth's layer", how: "Double definition" },
  minute: { clue: "Tiny: note, crackpot, energy", how: "MI (note) + NUT (crackpot) + E (energy)" },
  minuet: { clue: "Dance: least, you, and in Paris", how: "MIN (least) + U (you) + ET (French \"and\")" },
  mister: { clue: "Mr.: fog, hesitation", how: "MIST (fog) + ER (hesitation)" },
  merits: { clue: "Virtues: sea in Paris, its", how: "MER (French \"sea\") + ITS" },
  timers: { clue: "Clocks: Tiny ___, hesitations", how: "TIM (Tiny Tim) + ERS (hesitations)" },
  remits: { clue: "Sends: sleep phase, its", how: "REM (sleep phase) + ITS" },
  morals: { clue: "Ethics: minute, then spoken exams", how: "M (minute) + ORALS (spoken exams)" },
  molars: { clue: "Grinders: moment, Lars", how: "MO (moment) + LARS" },
  neural: { clue: "Of nerves: northeast, then Russian river", how: "NE (northeast) + URAL (Russian river)" },
  unreal: { clue: "Fake: \"a\" in Paris, genuine", how: "UN (French \"a\") + REAL (genuine)" },
  novels: { clue: "Books: new, son", how: "NOVEL (new) + S (son)" },
  sloven: { clue: "Slob: son, darling, new", how: "S (son) + LOVE (darling) + N (new)" },
  oceans: { clue: "Seas: zero, Common Era, answers", how: "O (zero) + CE (Common Era) + ANS (answers)" },
  canoes: { clue: "Boats: about refusals", how: "CA (about) + NOES (refusals)" },
  ordeal: { clue: "Trial: gold bargain", how: "OR (gold) + DEAL (bargain)" },
  loader: { clue: "Forklift, perhaps: look, fruit drink, right", how: "LO (look) + ADE (fruit drink) + R (right)" },
  reload: { clue: "Refresh: on, look, commercial", how: "RE (on) + LO (look) + AD (commercial)" },
  others: { clue: "The rest: male siblings, first two gone", how: "(br)OTHERS" },
  throes: { clue: "Spasms: pitches, we hear", how: "Sounds like THROWS (pitches)" },
  owners: { clue: "Holders: admit hesitations", how: "OWN (admit) + ERS (hesitations)" },
  worsen: { clue: "Deteriorate: poorer, new", how: "WORSE (poorer) + N (new)" },
  parcel: { clue: "Package: standard, film frame", how: "PAR (standard) + CEL (film frame)" },
  placer: { clue: "Gold deposit: spot, right", how: "PLACE (spot) + R (right)" },
  parent: { clue: "Mom, perhaps: norm, then ear doc", how: "PAR (norm) + ENT (ear doc)" },
  entrap: { clue: "Snare: printer's space, mouth", how: "EN (printer's space) + TRAP (mouth)" },
  partly: { clue: "Somewhat, in counterpart lyrics", how: "Hidden in counterPART LYrics" },
  paltry: { clue: "Meager: friend's attempt", how: "PAL (friend) + TRY (attempt)" },
  patron: { clue: "Backer: tap, then right on", how: "PAT (tap) + R (right) + ON" },
  tarpon: { clue: "Fish: canvas cover, on", how: "TARP (canvas cover) + ON" },
  planes: { clue: "Quiet paths for aircraft", how: "P (quiet) + LANES (paths)" },
  panels: { clue: "Groups: criticize trains", how: "PAN (criticize) + ELS (elevated railways)" },
  planet: { clue: "World: scheme and, in Paris", how: "PLAN (scheme) + ET (French \"and\")" },
  platen: { clue: "Roller: dish, new", how: "PLATE (dish) + N (new)" },
  plates: { clue: "Dishes: quiet, tardy son", how: "P (quiet) + LATE (tardy) + S (son)" },
  staple: { clue: "Fastener in past aplenty", how: "Hidden: paST APLEnty" },
  petals: { clue: "Flower parts in carpet also", how: "Hidden in carPET ALSo" },
  pastel: { clue: "Soft shade: over, then elevated train", how: "PAST (over) + EL (elevated train)" },
  pleats: { clue: "Folds: appeal, time, son", how: "PLEA (appeal) + T (time) + S (son)" },
  palest: { clue: "Most wan: friend established", how: "PAL (friend) + EST (established)" },
  player: { clue: "Gamer: drama, hesitation", how: "PLAY (drama) + ER (hesitation)" },
  replay: { clue: "Rerun concerning drama", how: "RE (concerning) + PLAY (drama)" },
  pearly: { clue: "Lustrous: gem, unknown", how: "PEARL (gem) + Y (unknown)" },
  posted: { clue: "Mailed: stake, editor", how: "POST (stake) + ED (editor)" },
  depots: { clue: "Warehouses hide pots, in part", how: "Hidden in hiDE POTS" },
  despot: { clue: "Tyrant: \"of the,\" in Paris, kitty", how: "DES (French \"of the\") + POT (kitty)" },
  poster: { clue: "Wall hanging: mail, hesitation", how: "POST (mail) + ER (hesitation)" },
  presto: { clue: "Magic word: publicity, established, ring", how: "PR (publicity) + EST (established) + O (ring)" },
  tropes: { clue: "Clichés: time lines", how: "T (time) + ROPES (lines)" },
  praise: { clue: "Laud quiet lift", how: "P (quiet) + RAISE (lift)" },
  aspire: { clue: "Aim high, a steeple", how: "A + SPIRE (steeple)" },
  priest: { clue: "Father: snoops, time", how: "PRIES (snoops) + T (time)" },
  stripe: { clue: "Band: peel off, energy", how: "STRIP (peel off) + E (energy)" },
  sprite: { clue: "Fairy: son, page, ceremony", how: "S (son) + P (page) + RITE (ceremony)" },
  ripest: { clue: "Most mature: tear, established", how: "RIP (tear) + EST (established)" },
  prince: { clue: "Heir: publish briefly, Common Era", how: "PRIN(t) + CE (Common Era)" },
  pincer: { clue: "Claw found in spin certainly", how: "Hidden: sPIN CERtainly" },
  prints: { clue: "Photos: publish, son", how: "PRINT (publish) + S (son)" },
  sprint: { clue: "Dash: son to publish", how: "S (son) + PRINT (to publish)" },
  remind: { clue: "Prompt on care", how: "RE (on) + MIND (care)" },
  minder: { clue: "Keeper: care, then hesitation", how: "MIND (care) + ER (hesitation)" },
  result: { clue: "Outcome in dire sultanate", how: "Hidden in diRE SULTanate" },
  luster: { clue: "Shine: desire, hesitation", how: "LUST (desire) + ER (hesitation)" },
  rustle: { clue: "Steal cattle: corrosion, \"the\" in Paris", how: "RUST (corrosion) + LE (French \"the\")" },
  retain: { clue: "Keep teaching assistant in check", how: "TA (teaching assistant) inside REIN (check)" },
  retina: { clue: "Eye part: about metal, a", how: "RE (about) + TIN (metal) + A" },
  rifles: { clue: "Ransacks Winchesters", how: "Double definition" },
  fliers: { clue: "Pilots: Florida, one, emergency rooms", how: "FL (Florida) + I (one) + ERS (emergency rooms)" },
  lifers: { clue: "Long-termers: existence, right, son", how: "LIFE (existence) + R (right) + S (son)" },
  rights: { clue: "Entitlements: correct, son", how: "RIGHT (correct) + S (son)" },
  girths: { clue: "Cinches or circumferences", how: "Double definition" },
  runway: { clue: "Catwalk: dash, path", how: "RUN (dash) + WAY (path)" },
  unwary: { clue: "Heedless: world body, then cautious", how: "UN (world body) + WARY (cautious)" },
  sample: { clue: "Taste: son, plenty", how: "S (son) + AMPLE (plenty)" },
  maples: { clue: "Syrup trees: chart \"the\" in Paris", how: "MAP (chart) + LES (French \"the\")" },
  scored: { clue: "Tallied: son, hollowed", how: "S (son) + CORED (hollowed)" },
  decors: { clue: "Styles: December golds", how: "DEC (December) + ORS (golds)" },
  coders: { clue: "Programmers: cipher, right, son", how: "CODE (cipher) + R (right) + S (son)" },
  credos: { clue: "Beliefs: about do-overs", how: "C (about) + REDOS (do-overs)" },
  scrape: { clue: "Graze: fight, energy", how: "SCRAP (fight) + E (energy)" },
  capers: { clue: "Antics: hat, hesitations", how: "CAP (hat) + ERS (hesitations)" },
  recaps: { clue: "Summaries about hats", how: "RE (about) + CAPS (hats)" },
  spacer: { clue: "Gap filler: room, right", how: "SPACE (room) + R (right)" },
  pacers: { clue: "Runners: rate, then right and son", how: "PACE (rate) + R (right) + S (son)" },
  scream: { clue: "Yell: son, the best", how: "S (son) + CREAM (the best)" },
  creams: { clue: "Lotions: about paper stacks", how: "C (about) + REAMS (paper stacks)" },
  search: { clue: "Hunt: scorch church", how: "SEAR (scorch) + CH (church)" },
  arches: { clue: "Bridge spans: curve, then males", how: "ARC (curve) + HES (males)" },
  chaser: { clue: "Pursuer: hunt, right", how: "CHASE (hunt) + R (right)" },
  senior: { clue: "Elder: senator, one, gold", how: "SEN (senator) + I (one) + OR (gold)" },
  nosier: { clue: "More prying: refusal, son, one, hesitation", how: "NO (refusal) + S (son) + I (one) + ER (hesitation)" },
  serial: { clue: "Episodic breakfast food, aloud", how: "Sounds like CEREAL" },
  sailer: { clue: "Ship: canvas, hesitation", how: "SAIL (canvas) + ER (hesitation)" },
  shared: { clue: "Split: son with rabbit, died", how: "S (son) + HARE (rabbit) + D (died)" },
  dasher: { clue: "Santa's reindeer: rush, then hesitation", how: "DASH (rush) + ER (hesitation)" },
  shovel: { clue: "Spade: son's shack", how: "S (son) + HOVEL (shack)" },
  hovels: { clue: "Shacks: hot books, first missing", how: "H (hot) + (n)OVELS" },
  shrine: { clue: "Holy place: hush, Rhine without H", how: "SH (hush) + R(h)INE" },
  shiner: { clue: "Black eye: gleam, right", how: "SHINE (gleam) + R (right)" },
  signal: { clue: "Blinker: notice, then aluminum", how: "SIGN (notice) + AL (aluminum)" },
  aligns: { clue: "Lines up: a, left, signs beheaded", how: "A + L (left) + (s)IGNS" },
  silver: { clue: "Second place in basil vermouth", how: "Hidden: baSIL VERmouth" },
  livers: { clue: "Organs: exist, right, son", how: "LIVE (exist) + R (right) + S (son)" },
  sliver: { clue: "Splinter: small bile producer", how: "S (small) + LIVER (bile producer)" },
  slower: { clue: "Less fast: son to drop", how: "S (son) + LOWER (to drop)" },
  lowers: { clue: "Drops: moo, hesitations", how: "LOW (moo) + ERS (hesitations)" },
  snatch: { clue: "Grab: son, naturally", how: "S (son) + NATCH (naturally, slang)" },
  chants: { clue: "Crowd cries: church insects", how: "CH (church) + ANTS (insects)" },
  solemn: { clue: "Grave: fish, Minnesota", how: "SOLE (fish) + MN (Minnesota)" },
  lemons: { clue: "Duds: sour fruit, son", how: "LEMON (sour fruit) + S (son)" },
  melons: { clue: "Honeydews in caramel on sundaes", how: "Hidden in caraMEL ON Sundaes" },
  sought: { clue: "Looked for: son should", how: "S (son) + OUGHT (should)" },
  toughs: { clue: "Thugs: toward sounds of disgust", how: "TO (toward) + UGHS" },
  spider: { clue: "Web weaver, or a solitaire game", how: "Double definition" },
  prides: { clue: "Lion groups: quiet trips", how: "P (quiet) + RIDES (trips)" },
  stance: { clue: "Posture seen in first ancestors", how: "Hidden in firST ANCEstors" },
  ascent: { clue: "Climb: a smell", how: "A + SCENT (smell)" },
  stared: { clue: "Gawked: celebrity editor", how: "STAR (celebrity) + ED (editor)" },
  trades: { clue: "Swaps occupations", how: "Double definition: trades (swaps) / trades (occupations)" },
  treads: { clue: "Steps: time studies", how: "T (time) + READS (studies)" },
  starve: { clue: "Go hungry: celebrity, very, energy", how: "STAR (celebrity) + V (very) + E (energy)" },
  averts: { clue: "Wards off: declare, time, son", how: "AVER (declare) + T (time) + S (son)" },
  streak: { clue: "Stripe: sirloin around right", how: "ST(R)EAK (steak around R, right)" },
  skater: { clue: "Rink athlete: fish, right", how: "SKATE (fish) + R (right)" },
  takers: { clue: "Buyers: grab, right, son", how: "TAKE (grab) + R (right) + S (son)" },
  strike: { clue: "Hit son's three-wheeler", how: "S (son) + TRIKE (three-wheeler)" },
  trikes: { clue: "Three-wheelers hits, first off", how: "(s)TRIKES" },
  stroke: { clue: "Brain attack or a golf swing", how: "Double definition" },
  stoker: { clue: "Fire feeder: street, fine, hesitation", how: "ST (street) + OK (fine) + ER (hesitation)" },
  subtle: { clue: "Faint: sandwich, title without it", how: "SUB (sandwich) + T(it)LE" },
  bustle: { clue: "Busy activity: sculpture, \"the\" in Paris", how: "BUST (sculpture) + LE (French \"the\")" },
  bluest: { clue: "Saddest: music, time", how: "BLUES (music) + T (time)" },
  sublet: { clue: "Rent out: sandwich, allow", how: "SUB (sandwich) + LET (allow)" },
  throne: { clue: "Seat: toss endlessly, northeast", how: "THRO(w) (toss, endlessly) + NE (northeast)" },
  hornet: { clue: "Wasp: trumpet and, in Paris", how: "HORN (trumpet) + ET (French \"and\")" },
  traced: { clue: "Copied: hint, then daughter", how: "TRACE (hint) + D (daughter)" },
  redact: { clue: "Censor: communist law", how: "RED (communist) + ACT (law)" },
  traces: { clue: "Hints: time, heats", how: "T (time) + RACES (heats)" },
  crates: { clue: "Boxes: about prices", how: "C (about) + RATES (prices)" },
  caster: { clue: "Furniture wheel: social class, right", how: "CASTE (social class) + R (right)" },
  reacts: { clue: "Responds about deeds", how: "RE (about) + ACTS (deeds)" },
  recast: { clue: "Remake: about, mold", how: "RE (about) + CAST (mold)" },
  trance: { clue: "Daze: time fled, Common Era", how: "T (time) + RAN (fled) + CE (Common Era)" },
  nectar: { clue: "Bee food: northeast, about, sailor", how: "NE (northeast) + C (about) + TAR (sailor)" },
  canter: { clue: "Easy gait: jargon, hesitation", how: "CANT (jargon) + ER (hesitation)" },
  recant: { clue: "Retract about jargon", how: "RE (about) + CANT (jargon)" },
  trials: { clue: "Tests: time, Iranian coins", how: "T (time) + RIALS (Iranian coins)" },
  trails: { clue: "Paths: time, bars", how: "T (time) + RAILS (bars)" },
  tribes: { clue: "Clans: time to tease, 'is' in Madrid", how: "T (time) + RIB (tease) + ES (Spanish \"is\")" },
  biters: { clue: "Nippers: snack, right, son", how: "BITE (snack) + R (right) + S (son)" },
  unable: { clue: "Powerless: \"a\" in Paris, competent", how: "UN (French \"a\") + ABLE (competent)" },
  nebula: { clue: "Star cloud: northeast, book, university, L.A.", how: "NE (northeast) + B (book) + U (university) + LA" },
  voters: { clue: "Electors: ballot, right, son", how: "VOTE (ballot) + R (right) + S (son)" },
  strove: { clue: "Tried son's treasure", how: "S (son) + TROVE (treasure)" },
  troves: { clue: "Hoards: time wanders", how: "T (time) + ROVES (wanders)" },
  waters: { clue: "Seas: west, dined, right, son", how: "W (west) + ATE (dined) + R (right) + S (son)" },
  waster: { clue: "Spendthrift: west, then fall flower", how: "W (west) + ASTER (fall flower)" },
  winter: { clue: "Cold season: west, bury", how: "W (west) + INTER (bury)" },
  twiner: { clue: "Climbing vine: double, hesitation", how: "TWIN (double) + ER (hesitation)" },
  wolves: { clue: "Pack animals: west cracks, first off", how: "W (west) + (s)OLVES (cracks)" },
  vowels: { clue: "A and I, say: pledge, elevated trains", how: "VOW (pledge) + ELS (elevated trains)" },
  wonder: { clue: "Marvel: triumphed, \"the\" in Berlin", how: "WON (triumphed) + DER (German \"the\")" },
  downer: { clue: "Buzzkill: feathers, hesitation", how: "DOWN (feathers) + ER (hesitation)" },
};
