/**
 * One true cryptic clue per answer word: a definition at one end plus
 * wordplay that builds the answer another way. `how` is the parse — shown
 * on the results card after a cryptic day, and what a reviewer checks.
 *
 * No ANAGRAM cryptics: the letter pad already shows the six letters, so
 * "shuffled" wordplay would hand the answer over. The toolkit is charades
 * (A + B), containers, hidden words, sound-alikes, deletions and — where a
 * word resists — an honest double definition.
 *
 * Conventional abbreviations: ED editor, ER hesitation, RS Royal Society,
 * EL elevated railway, S son, T time, D died, R right, C about, RE on/about,
 * EST establishment, OR gold, CE Church of England, CH church, ST street;
 * DE/LE/LES/UN/ET/FIN/MER are French, ES/SI Spanish, DER German.
 *
 * AI-written, then two AI editor passes (every charade and hidden word
 * checked against its answer mechanically), then restyled to the owner's
 * taste and spot-reviewed; accepted for launch.
 */
export interface Cryptic {
  clue: string;
  how: string;
}

export const CRYPTIC: Readonly<Record<string, Cryptic>> = {
  angels: { clue: "Heavenly hosts backing startups", how: "Double definition" },
  angles: { clue: "Fishes for viewpoints", how: "Double definition: angles (fishes) / angles (viewpoints)" },
  begins: { clue: "Starts to exist on spirits", how: "BE (to exist) + GINS (spirits)" },
  beings: { clue: "Pleads to keep in creatures", how: "BE(IN)GS: IN inside BEGS (pleads)" },
  brakes: { clue: "Car stoppers sound like recesses", how: "Sounds like BREAKS (recesses)" },
  breaks: { clue: "Fractures or lucky chances", how: "Double definition" },
  burden: { clue: "Load: prickly seed head beside lair", how: "BUR (prickly seed head) + DEN (lair)" },
  burned: { clue: "Scorched some Auburn edifices", how: "Hidden in auBURN EDifices" },
  caring: { clue: "Oscar in green is partly kind", how: "Hidden in osCAR IN Green" },
  racing: { clue: "Sport of kings, pounding", how: "Double definition" },
  course: { clue: "Dish: swear word holding a ring", how: "CURSE (swear word) holding O (ring)" },
  source: { clue: "Origin found in sour cereal", how: "Hidden in SOUR CEreal" },
  credit: { clue: "Believe the tribute", how: "Double definition: believe / tribute" },
  direct: { clue: "Steer straight", how: "Double definition: steer / straight" },
  danger: { clue: "Peril is daughter's rage", how: "D (daughter) + ANGER" },
  garden: { clue: "Fish before lair, where roses grow", how: "GAR (fish) + DEN (lair)" },
  denial: { clue: "Refusal in Camden, I allege", how: "Hidden in (Cam)DEN I AL(lege)" },
  nailed: { clue: "Caught red-handed and aced", how: "Double definition: NAILED (caught red-handed) / NAILED (aced)" },
  depart: { clue: "Leave some chef-made partridge", how: "Hidden in chef-maDE PARTridge (D-E-P-A-R-T)" },
  parted: { clue: "Split up and combed to one side", how: "Double definition: PARTED (split up) / PARTED (of hair, combed to one side)" },
  design: { clue: "Pattern found in jade signet rings", how: "Hidden in jaDE SIGNet" },
  signed: { clue: "Autographed notice for the editor", how: "SIGN (notice) + ED (editor)" },
  duties: { clue: "Tariffs of the French bonds", how: "DU (\"of the\" in French) + TIES (bonds)" },
  suited: { clue: "Case for Ed was fitting", how: "SUIT (case, as in lawsuit) + ED" },
  equals: { clue: "Matches peers", how: "Double definition: matches (v.) / peers (n.)" },
  squeal: { clue: "Rat, or a pig's cry", how: "Double definition" },
  escort: { clue: "Date spotted in the bride's cortege", how: "Hidden in bridE'S CORTege" },
  sector: { clue: "Zone: cult with gold", how: "SECT (cult) + OR (gold)" },
  forest: { clue: "Golf warning by street leads to woods", how: "FORE (golf warning) + ST (street)" },
  foster: { clue: "Promote actress Jodie", how: "Double definition (promote / Jodie FOSTER)" },
  groans: { clue: "Moans: good horses", how: "G (good) + ROANS (horses)" },
  organs: { clue: "Hearts, say, found in Morgan Stanley", how: "Hidden in mORGAN Stanley" },
  hatred: { clue: "Loathing hidden in chat, redacted", how: "Hidden in cHAT REDacted (H-A-T-R-E-D)" },
  thread: { clue: "Weave through a string of posts", how: "Double definition: THREAD (weave through, as with a needle) / THREAD (a string of online posts)" },
  hostel: { clue: "Backpacker's inn for party giver on the El", how: "HOST (party giver) + EL (the El)" },
  hotels: { clue: "Inns by popular Chicago trains", how: "HOT (popular) + ELS (Chicago trains)" },
  ideals: { clue: "One trades principles", how: "I (one) + DEALS (trades)" },
  ladies: { clue: "Women: L.A. expires", how: "LA + DIES" },
  sailed: { clue: "Cruised in the salsa I led", how: "Hidden in salSA I LED (S-A-I-L-E-D)" },
  ignore: { clue: "Brush off part of a big nor'easter", how: "Hidden in bIG NOR'Easter" },
  region: { clue: "Zone where Reg meets a charged atom", how: "REG (a name) + ION (charged atom)" },
  insect: { clue: "Bug at home with a cult", how: "IN (at home) + SECT (cult)" },
  nicest: { clue: "Riviera city street is kindest", how: "NICE (Riviera city) + ST (street)" },
  antler: { clue: "Rack part seen in elegant Lerner musical", how: "Hidden in elegANT LERner" },
  rental: { clue: "Leased car caught in torrent alert", how: "Hidden in torRENT ALert" },
  lights: { clue: "Ignites lamps", how: "Double definition: LIGHTS (ignites) / LIGHTS (lamps)" },
  slight: { clue: "Minor insult", how: "Double definition: SLIGHT (minor) / SLIGHT (insult)" },
  listen: { clue: "Hear a creditor's claim about the street", how: "LI(ST)EN: ST (street) inside LIEN (creditor's claim)" },
  silent: { clue: "Some fossil entombed without a sound", how: "Hidden in fosSIL ENTombed" },
  lowest: { clue: "Least high? Look west!", how: "LO (look) + WEST" },
  towels: { clue: "Dryers in a photo, Welsh seaside", how: "Hidden in phoTO WELSh" },
  marine: { clue: "Of the sea, or a leatherneck", how: "Double definition" },
  remain: { clue: "Stay on the sea", how: "RE (on) + MAIN (the sea)" },
  master: { clue: "Get the hang of the original", how: "Double definition: get the hang of / the original (recording)" },
  stream: { clue: "Brook: street with paper", how: "ST (street) + REAM (paper)" },
  models: { clue: "Poses for painters and shapes clay", how: "Double definition: POSES FOR PAINTERS / SHAPES CLAY" },
  seldom: { clue: "Rarely found in diesel domestic cars", how: "Hidden in dieSEL DOMestic" },
  nights: { clue: "Chessmen losing their king in the evenings", how: "(k)NIGHTS: KNIGHTS (chessmen) minus K (king)" },
  things: { clue: "Stuff in a clothing store", how: "Hidden in cloTHING Store" },
  patrol: { clue: "Beat: tap, then roll cut short", how: "PAT (tap) + ROL(l)" },
  portal: { clue: "Harbor Al at the gateway", how: "PORT (harbor) + AL" },
  pilots: { clue: "Greek letter gets plenty of TV tryouts", how: "PI (Greek letter) + LOTS (plenty)" },
  pistol: { clue: "Harpist Olga holds a starter's gun", how: "Hidden in harPIST OLga" },
  plains: { clue: "Aircraft heard over the prairies", how: "Sounds like PLANES (aircraft)" },
  spinal: { clue: "Twirl Al, like a certain cord", how: "SPIN (twirl) + AL" },
  ransom: { clue: "Kidnap payment seen as Fran somersaults", how: "Hidden in fRAN SOMersaults" },
  romans: { clue: "Old Italians, or an epistle", how: "Double definition: old Italians / an epistle (Book of Romans)" },
  resign: { clue: "Quit about a notice", how: "RE (about) + SIGN (notice)" },
  singer: { clue: "Vocalist seen crossing Erie", how: "Hidden in crosSING ERie" },
  sacred: { clue: "Holy pouch, like a cardinal", how: "SAC (pouch) + RED (like a cardinal)" },
  scared: { clue: "Spooked by some Oscar editors", how: "Hidden in oSCAR EDitors" },
  spared: { clue: "Saved when the resort went Red", how: "SPA (resort) + RED (Communist)" },
  spread: { clue: "Lavish meal on a ranch", how: "Double definition: spread (lavish meal) / spread (ranch)" },
  stable: { clue: "Steady small piece of furniture", how: "S (small) + TABLE (furniture)" },
  tables: { clue: "Charts: bill with \"the,\" in Paris", how: "TAB (bill) + LES (French \"the\")" },
  stayed: { clue: "Remained, or halted by court order", how: "Double definition: STAYED (remained) / STAYED (halted by court order, as an execution)" },
  steady: { clue: "Firm place, unknown", how: "STEAD (place) + Y (unknown)" },
  strain: { clue: "Melody filter", how: "Double definition: melody / filter" },
  trains: { clue: "Coaches for commuters", how: "Double definition: coaches (v.) / things for commuters (n.)" },
  struck: { clue: "Hit small rig", how: "S (small) + TRUCK (rig)" },
  trucks: { clue: "Rigs hidden in that rucksack", how: "Hidden in thaT RUCKSack" },
  wander: { clue: "Stray from the Taiwan derby", how: "Hidden in TaiWAN DERby (W-A-N-D-E-R)" },
  warden: { clue: "Prison keeper holding Edward entranced", how: "Hidden in EdWARD ENtranced (W-A-R-D-E-N)" },
  warned: { clue: "Cautioned charge about New England", how: "WAR(NE)D: NE (New England) inside WARD (charge)" },
  actors: { clue: "Players found in fact or superstition", how: "Hidden in f(ACT OR S)uperstition" },
  costar: { clue: "Fellow lead in Costa Rica", how: "Hidden in COSTA Rica" },
  castor: { clue: "Gemini star: throw gold", how: "CAST (throw) + OR (gold)" },
  aliens: { clue: "Outsiders found in Bali ensembles", how: "Hidden in BALI ENSembles (A-L-I-E-N-S)" },
  saline: { clue: "Salty Sound holding Long Island", how: "SA(LI)NE: LI (Long Island) inside SANE (sound, of mind)" },
  ashore: { clue: "On land: a coast", how: "A + SHORE (coast)" },
  hoarse: { clue: "Croaky mount, we hear", how: "Sounds like HORSE (mount)" },
  badger: { clue: "Pester: evil German", how: "BAD (evil) + GER (German)" },
  barged: { clue: "Pushed in: boat, then daughter", how: "BARGE (boat) + D (daughter)" },
  barely: { clue: "Only just, in a naked way", how: "BARE (naked) + LY (in a ... way)" },
  barley: { clue: "Grain: bachelor on headless Harley", how: "B (bachelor) + (h)ARLEY (Harley, headless)" },
  bleary: { clue: "Dim-eyed: tragic king kept inside \"by\"", how: "B(LEAR)Y: LEAR (tragic king) inside BY" },
  blamed: { clue: "Faulted for limping inside heartless bed", how: "B(LAME)D: LAME (limping) inside B(e)D (heartless bed)" },
  bedlam: { clue: "Uproar: garden plot with lamb, tail docked", how: "BED (garden plot) + LAM(b) (lamb, tail docked)" },
  boiler: { clue: "Tank that's always in hot water", how: "Cryptic definition: a hot-water tank; 'in hot water' = in trouble" },
  reboil: { clue: "Heat again in Zagreb oil plant", how: "Hidden in zagREB OIL" },
  breast: { clue: "Chest: relax after bedtime begins", how: "B (bedtime begins) + REST (relax)" },
  barest: { clue: "Most minimal: pub, Eastern time", how: "BAR (pub) + EST (Eastern Standard Time)" },
  breath: { clue: "Air: endless loaf with half of this", how: "BREA(d) (loaf, endless) + TH(is) (half of this)" },
  bather: { clue: "Swimmer: flying mammal, then that woman", how: "BAT (flying mammal) + HER (that woman)" },
  bridal: { clue: "Of a wedding, horse's headgear, we hear", how: "Sounds like BRIDLE" },
  ribald: { clue: "Racy: Rhode Island, hairless", how: "RI (Rhode Island) + BALD (hairless)" },
  bruise: { clue: "Mark left by beers, we hear", how: "Sounds like BREWS (beers)" },
  buries: { clue: "Inters fruits, we hear", how: "Sounds like BERRIES" },
  busier: { clue: "Shaggier without husband? More hectic!", how: "BUS(H)IER: BUSHIER (shaggier) minus H (husband)" },
  rubies: { clue: "Hicks pocket one for red gems", how: "RUB(I)ES: I (one) inside RUBES (hicks)" },
  busted: { clue: "Broke and caught", how: "Double definition: broke / caught" },
  debuts: { clue: "Premieres: IOUs taking in university", how: "DEB(U)TS: U (university) inside DEBTS (IOUs)" },
  buster: { clue: "Pal found in bus terminal", how: "Hidden in BUS TERminal" },
  brutes: { clue: "Beasts and big bullies", how: "Double definition: beasts / big bullies" },
  tubers: { clue: "Pipes around river yield potatoes", how: "TUBE(R)S: R (river) inside TUBES (pipes)" },
  rebuts: { clue: "Counters about objections", how: "RE (about) + BUTS (objections)" },
  candle: { clue: "Light: why leaves sweet before Parisian \"the\"", how: "CAND(y) (sweet, losing Y, \"why\") + LE (\"the\" in Paris)" },
  lanced: { clue: "Pierced: spear, five hundred", how: "LANCE (spear) + D (five hundred, Roman numeral)" },
  cartel: { clue: "Ring: wagon on elevated railway", how: "CART (wagon) + EL (elevated railway)" },
  claret: { clue: "Wine from Irish county's first tasting", how: "CLARE (Irish county) + T (first of Tasting)" },
  castle: { clue: "Throw the French a stronghold", how: "CAST (throw) + LE (the, French)" },
  cleats: { clue: "Shoes found in uncle at sea", how: "Hidden: unCLE AT Sea" },
  chains: { clue: "Stores fetters", how: "Double definition: CHAINS (stores, as retail groups) / CHAINS (fetters)" },
  chinas: { clue: "Fine dishes some urchin assembled", how: "Hidden in urCHIN ASsembled" },
  charts: { clue: "Graphs about deer", how: "C (about) + HARTS (deer)" },
  starch: { clue: "Stiffener found in best archery", how: "Hidden in beST ARCHery" },
  cinema: { clue: "Movie house in vaccine maker", how: "Hidden in vacCINE MAker" },
  anemic: { clue: "Weak part of a plane microwave meal", how: "Hidden in plANE MICrowave" },
  iceman: { clue: "Cool character in police manhunt", how: "Hidden in polICE MANhunt" },
  clears: { clue: "Removes some nuclear science", how: "Hidden in nuCLEAR Science" },
  scaler: { clue: "Wall climber at the dentist's", how: "Double definition: SCALER (wall climber) / SCALER (dental tool, \"at the dentist's\")" },
  cursed: { clue: "Swore, being doomed", how: "Double definition: swore / doomed" },
  crudes: { clue: "Oils found in ecru desert sands", how: "Hidden in eCRU DESert" },
  dancer: { clue: "Hoofer, or one of Santa's team", how: "Double definition: dancer (hoofer) / Dancer (a reindeer)" },
  craned: { clue: "Rubbernecked like a bird would", how: "CRANE (bird) + 'D (would, as in \"it'd\")" },
  dances: { clue: "Cuts a rug at balls", how: "Double definition: DANCES (cuts a rug) / DANCES (balls)" },
  ascend: { clue: "Climb while a hundred finish", how: "AS (while) + C (a hundred) + END (finish)" },
  deacon: { clue: "Church officer: drug agency, trick", how: "DEA (drug agency) + CON (trick)" },
  canoed: { clue: "Paddled: small boat, then Democrat", how: "CANOE (small boat) + D (Democrat)" },
  debris: { clue: "Wreckage left in stampede, briskly", how: "Hidden in stampeDE BRISkly" },
  brides: { clue: "Newlyweds seen in cab rides home", how: "Hidden in caB RIDES" },
  detail: { clue: "Itemize the Secret Service squad", how: "Double definition: DETAIL (itemize) / DETAIL (a Secret Service protection squad)" },
  dilate: { clue: "Widen: cube holding back muscle", how: "DIE (cube) around LAT (back muscle)" },
  tailed: { clue: "Followed, in part, what ailed him", how: "Hidden in whaT AILED him (T-A-I-L-E-D)" },
  detour: { clue: "Bypass made tourists late, in part", how: "Hidden in maDE TOURists" },
  routed: { clue: "Crushed: defeat for the editor", how: "ROUT (defeat) + ED (editor)" },
  toured: { clue: "Trip with Ed saw the sights", how: "TOUR (trip) + ED" },
  diaper: { clue: "Baby wear in Wikipedia, perhaps", how: "Hidden in WikipeDIA PERhaps (D-I-A-P-E-R)" },
  paired: { clue: "Matched: quietly broadcast", how: "P (quiet, piano) + AIRED (broadcast)" },
  repaid: { clue: "Settled up with salesman's help", how: "REP (salesman) + AID (help)" },
  donate: { clue: "Mob boss dined, so chip in", how: "DON (mob boss) + ATE (dined)" },
  atoned: { clue: "Made amends, in part, for what one did", how: "Hidden in whAT ONE Did (A-T-O-N-E-D)" },
  drives: { clue: "Tee shots and ambitions", how: "Double definition: TEE SHOTS / AMBITIONS" },
  divers: { clue: "Various pearl hunters", how: "Double definition: VARIOUS (archaic \"divers\") / PEARL HUNTERS" },
  drones: { clue: "Male bees: doctor's singles", how: "DR (doctor) + ONES (singles)" },
  snored: { clue: "Sawed logs in forests, no redwoods", how: "Hidden in forestS NO REDwoods" },
  editor: { clue: "Newspaper boss seen in credit order", how: "Hidden in crEDIT ORder" },
  rioted: { clue: "Rampaged: a real hoot, with Ed tagging along", how: "RIOT (a real hoot) + ED" },
  triode: { clue: "Three before a lyric poem makes a tube", how: "TRI (three) + ODE (lyric poem)" },
  failed: { clue: "Went bust as the chef ailed, in part", how: "Hidden in cheF AILED" },
  afield: { clue: "A meadow far away", how: "A + FIELD (meadow)" },
  faster: { clue: "Quicker abstainer", how: "Double definition: quicker / one who fasts" },
  strafe: { clue: "Rake with fire, or sidestep shooting", how: "Double definition" },
  filter: { clue: "Strainer, or a photo effect", how: "Double definition" },
  lifter: { clue: "Bench presser or pickpocket", how: "Double definition: BENCH PRESSER / PICKPOCKET (a lifter)" },
  trifle: { clue: "Small matter: time for a gun", how: "T (time) + RIFLE (gun)" },
  finest: { clue: "Parking ticket on street is best", how: "FINE (parking ticket) + ST (street)" },
  infest: { clue: "Overrun: at home with a festival", how: "IN (at home) + FEST (festival)" },
  finger: { clue: "Accuse one of ten", how: "Double definition: ACCUSE / ONE OF TEN (a digit)" },
  fringe: { clue: "Band held by iron on the edge", how: "F(RING)E: RING (band) inside FE (iron)" },
  forces: { clue: "Makes troops", how: "Double definition: MAKES (compels) / TROOPS (armed forces)" },
  fresco: { clue: "Endlessly new company's wall art", how: "FRES(h) (new, endlessly: FRESH minus its last letter) + CO (company)" },
  formed: { clue: "Shaped tax document for editor", how: "FORM (tax document) + ED (editor)" },
  deform: { clue: "Warp found in homemade formula", how: "Hidden in homemaDE FORMula" },
  freaks: { clue: "Oddballs panic", how: "Double definition: freaks (oddballs) / freaks (panics, informal)" },
  fakers: { clue: "Phonies hide in the sofa Kershaw sat on", how: "Hidden in soFA KERShaw (F-A-K-E-R-S)" },
  friend: { clue: "Pal: Friday, then finish", how: "FRI (Friday) + END (finish)" },
  finder: { clue: "Lucky discoverer, or camera's eyepiece", how: "Double definition: LUCKY DISCOVERER / CAMERA EYEPIECE (viewfinder)" },
  gifted: { clue: "Talented: present for the editor", how: "GIFT (present) + ED (editor)" },
  fidget: { clue: "Squirm: Fido docked, then obtain", how: "FID(o) (Fido, tail docked) + GET (obtain)" },
  golden: { clue: "Gilded in big olden days", how: "Hidden: biG OLDEN days" },
  longed: { clue: "Pined for tall Ed", how: "LONG (tall) + ED" },
  grapes: { clue: "Vine fruit: Greek mimics", how: "GR (Greek) + APES (mimics)" },
  pagers: { clue: "Beepers seen in page RSVPs", how: "Hidden in (PAGE RS)VPs" },
  grunts: { clue: "Foot soldiers: good weaklings", how: "G (good) + RUNTS (weaklings)" },
  strung: { clue: "Threaded: street step", how: "ST (street) + RUNG (step)" },
  hearts: { clue: "That man crafts suit", how: "HE (that man) + ARTS (crafts)" },
  earths: { clue: "Soils beheaded fireplaces", how: "(h)EARTHS: HEARTHS (fireplaces) with the head removed" },
  haters: { clue: "Critics in that ersatz coffee", how: "Hidden in (t)HAT ERS(atz)" },
  hustle: { clue: "Hurry, or a con", how: "Double definition" },
  sleuth: { clue: "Private eye, or to track", how: "Double definition" },
  images: { clue: "Pictures, or public reputations", how: "Double definition: images (pictures) / images (reputations)" },
  ageism: { clue: "Bias in sage is modest", how: "Hidden in (s)AGE IS M(odest)" },
  inches: { clue: "Measures kept in cabin chests", how: "Hidden in cabIN CHESts" },
  niches: { clue: "Nooks found in Munich estates", how: "Hidden: muNICH ESTates" },
  insult: { clue: "Offend some in sultry weather", how: "Hidden in IN SULTry" },
  sunlit: { clue: "Star alight and bright", how: "SUN (star) + LIT (alight)" },
  itself: { clue: "The tag chaser's ego, all by ___", how: "IT (the chaser in tag) + SELF (ego)" },
  stifle: { clue: "Suppress, in part, the cost if left unpaid", how: "Hidden in coST IF LEft" },
  filets: { clue: "Cuts seen if I let Sam carve", how: "Hidden in iF I LET Sam" },
  lasted: { clue: "Endured some Dallas TED talk", how: "Hidden in DalLAS TED talk (L-A-S-T-E-D)" },
  deltas: { clue: "Changes at river mouths", how: "Double definition: DELTAS (changes, as in math) / DELTAS (river mouths)" },
  layers: { clue: "Hens and onion parts", how: "Double definition: hens / onion parts" },
  relays: { clue: "Passes on about songs", how: "RE (about) + LAYS (songs)" },
  slayer: { clue: "Southern hen's a real killer", how: "S (Southern) + LAYER (hen)" },
  layout: { clue: "Plan found in kids' play outside", how: "Hidden in pLAY OUTside" },
  outlay: { clue: "Expense seen in scout Layla's gear", how: "Hidden in scOUT LAYla" },
  linked: { clue: "Connected, left tattooed", how: "L (left) + INKED (tattooed)" },
  kindle: { clue: "Light type of article in Paris", how: "KIND (type) + LE (article in Paris)" },
  listed: { clue: "Itemized, or leaned at sea", how: "Double definition: ITEMIZED / LEANED AT SEA (as a ship)" },
  delist: { clue: "Remove from sale in handmade listings", how: "Hidden in handmaDE LISTings" },
  locker: { clue: "Secure emergency room storage", how: "LOCK (secure) + ER (emergency room)" },
  relock: { clue: "Bolt again about a tress", how: "RE (about) + LOCK (tress)" },
  lovers: { clue: "Sweethearts in a pullover sweater", how: "Hidden in pulLOVER Sweater" },
  solver: { clue: "Puzzle whiz in parasol, very relaxed", how: "Hidden in paraSOL VERy" },
  maiden: { clue: "Mermaid enters, hiding a young woman", how: "Hidden in merMAID ENters (M-A-I-D-E-N)" },
  median: { clue: "Middle held by a boy named Ian", how: "Hidden in naMED IAN (M-E-D-I-A-N)" },
  marble: { clue: "Stone found in grammar blends", how: "Hidden in gramMAR BLEnds" },
  ramble: { clue: "Wander: right stroll", how: "R (right) + AMBLE (stroll)" },
  medals: { clue: "Honors in famed Alsace wines", how: "Hidden in fa(MED ALS)ace" },
  damsel: { clue: "Young lady found in Adam's elbow?", how: "Hidden in aDAM'S ELbow (D-A-M-S-E-L), a nod to Eve and the rib" },
  mental: { clue: "Guys not quite tall? All in the mind", how: "MEN (guys) + TAL(l) (not quite tall)" },
  lament: { clue: "Dirge in what Paula mentioned", how: "Hidden in PauLA MENTioned (L-A-M-E-N-T)" },
  mantle: { clue: "Cloak, or the earth's layer", how: "Double definition" },
  minute: { clue: "Tiny moment", how: "Double definition: MINUTE (tiny) / MINUTE (moment)" },
  minuet: { clue: "E.T. trails less, mostly, in a stately dance", how: "MINU(s) (less, mostly) + ET (E.T.)" },
  mister: { clue: "Plant sprayer, or sir", how: "Double definition: MISTER (plant sprayer) / MISTER (sir)" },
  merits: { clue: "Virtues found in summer itself", how: "Hidden in sumMER ITSelf" },
  timers: { clue: "Track officials, or kitchen clocks", how: "Double definition: TIMERS (race timekeepers) / TIMERS (kitchen clocks)" },
  remits: { clue: "Sends money, or lets off", how: "Double definition: REMITS (sends money) / REMITS (lets off, pardons)" },
  morals: { clue: "Ethics? There's some in humor also", how: "Hidden in huMOR ALSo" },
  molars: { clue: "They chew the fat at the back", how: "Cryptic definition: back teeth chew (fat); 'chew the fat' = chat" },
  neural: { clue: "Of nerves, being impartial, heartlessly", how: "NEU(T)RAL: NEUTRAL (impartial) minus its heart T" },
  unreal: { clue: "Nice one, genuine — fantastic!", how: "UN (one, in Nice) + REAL (genuine)" },
  novels: { clue: "Carols holding five books", how: "NO(V)ELS: V (five) inside NOELS (carols)" },
  sloven: { clue: "Slob found in this love nest", how: "Hidden in thiS LOVE Nest" },
  oceans: { clue: "Lots of seas", how: "Double definition: OCEANS (lots, as in \"oceans of time\") / OCEANS (seas)" },
  canoes: { clue: "Boats found in volcano escape", how: "Hidden in volCANO EScape" },
  ordeal: { clue: "Trial: gold bargain", how: "OR (gold) + DEAL (bargain)" },
  loader: { clue: "Front-end worker on a building site?", how: "Cryptic definition: a front-end LOADER is a building-site machine (misdirecting toward a front-end developer)" },
  reload: { clue: "Refresh, about a ton of work", how: "RE (about) + LOAD (a ton of work)" },
  others: { clue: "Headless moms? The rest", how: "(m)OTHERS: MOTHERS (moms) minus first letter" },
  throes: { clue: "Spasms: pitches, we hear", how: "Sounds like THROWS (pitches)" },
  owners: { clue: "Proprietors of headless buzzkills", how: "(d)OWNERS: DOWNERS (buzzkills) minus first letter" },
  worsen: { clue: "Go downhill, frayed around the Southeast", how: "WOR(SE)N: SE (Southeast) inside WORN (frayed)" },
  parcel: { clue: "Package hidden in a par celebration", how: "Hidden in PAR CELebration" },
  placer: { clue: "Gold deposit found in fireplace rug", how: "Hidden in firePLACE Rug" },
  parent: { clue: "Mom, maybe, with Pop ripped", how: "PA (Pop) + RENT (ripped)" },
  entrap: { clue: "Snare found in decent rap", how: "Hidden in decENT RAP" },
  partly: { clue: "Somewhat, seen as we depart Lyon", how: "Hidden in dePART LYon" },
  paltry: { clue: "Meager: friend's attempt", how: "PAL (friend) + TRY (attempt)" },
  patron: { clue: "Tap Ron, a regular", how: "PAT (tap) + RON" },
  tarpon: { clue: "Fish found in Qatar ponds", how: "Hidden in qaTAR PONds" },
  planes: { clue: "Quiet paths for aircraft", how: "P (quiet) + LANES (paths)" },
  panels: { clue: "Groups: criticize trains", how: "PAN (criticize) + ELS (elevated railways)" },
  planet: { clue: "Design alien world", how: "PLAN (design) + ET (alien)" },
  platen: { clue: "Roller: scheme to surround tight end", how: "PLA(TE)N: TE (tight end) inside PLAN (scheme)" },
  plates: { clue: "Dishes found in hip-hop late show", how: "Hidden in hip-hoP LATE Show" },
  staple: { clue: "Rice, perhaps, old but keeping quiet", how: "STA(P)LE: P (quiet) inside STALE (old)" },
  petals: { clue: "Rose parts in pet Alsatian's coat", how: "Hidden in PET ALSatian" },
  pastel: { clue: "Bygone Spanish article in a soft shade", how: "PAST (bygone) + EL (Spanish article)" },
  pleats: { clue: "Folds seen in purple at sunset", how: "Hidden in purPLE AT Sunset" },
  palest: { clue: "Most wan, found in Nepal estate", how: "Hidden in nePAL ESTate" },
  player: { clue: "Gamer spotted in display errors", how: "Hidden in disPLAY ERrors" },
  replay: { clue: "Rerun concerning drama", how: "RE (concerning) + PLAY (drama)" },
  pearly: { clue: "Lustrous layer that takes in an ear", how: "P(EAR)LY: EAR inside PLY (layer)" },
  posted: { clue: "Mailed, or stationed abroad", how: "Double definition: MAILED / STATIONED ABROAD" },
  depots: { clue: "Stores kept in homemade pots", how: "Hidden in homemaDE POTS" },
  despot: { clue: "A palace made spotless holds a tyrant", how: "Hidden in maDE SPOTless" },
  poster: { clue: "Forum commenter's wall hanging", how: "Double definition: POSTER (forum commenter) / POSTER (wall hanging)" },
  presto: { clue: "Quickly nap inside the post office", how: "P(REST)O: REST (nap) inside PO (post office)" },
  tropes: { clue: "Some metro pests are clichés", how: "Hidden in meTRO PESts" },
  praise: { clue: "Laud quiet lift", how: "P (quiet) + RAISE (lift)" },
  aspire: { clue: "Aim high, a steeple", how: "A + SPIRE (steeple)" },
  priest: { clue: "Father hiding in a Capri estate", how: "Hidden in caPRI ESTate" },
  stripe: { clue: "Journey through the Southeast earns a chevron", how: "S(TRIP)E: TRIP (journey) inside SE (Southeast)" },
  sprite: { clue: "Fairy's malice, taking in the queen", how: "SP(R)ITE: R (queen) inside SPITE (malice)" },
  ripest: { clue: "The readiest part of a trip estimate", how: "Hidden in tRIP ESTimate" },
  prince: { clue: "Cost swallowing new royal", how: "PRI(N)CE: N (new) inside PRICE (cost)" },
  pincer: { clue: "Claw, part of a grip in certain crabs", how: "Hidden in griP IN CERtain" },
  prints: { clue: "Publishes photos", how: "Double definition: PRINTS (publishes) / PRINTS (photos)" },
  sprint: { clue: "Tear through a short race", how: "Double definition: SPRINT (tear, rush) / SPRINT (short race)" },
  remind: { clue: "Prompt on care", how: "RE (on) + MIND (care)" },
  minder: { clue: "Watch emergency room, babysitter!", how: "MIND (watch) + ER (emergency room)" },
  result: { clue: "Score some pure sultanas", how: "Hidden in puRE SULTanas" },
  luster: { clue: "Headless grape bunch still has shine", how: "(c)LUSTER: CLUSTER (grape bunch) minus first letter" },
  rustle: { clue: "Steal cattle held by trust leaders", how: "Hidden in tRUST LEaders" },
  retain: { clue: "Keep teaching assistant in check", how: "TA (teaching assistant) inside REIN (check)" },
  retina: { clue: "Secret in a drawer hides eye part", how: "Hidden in secRET IN A drawer (R-E-T-I-N-A)" },
  rifles: { clue: "Ransacks Winchesters", how: "Double definition" },
  fliers: { clue: "Pilots' handouts", how: "Double definition: PILOTS / HANDOUTS" },
  lifers: { clue: "Some serve; some serve time", how: "Double definition: career soldiers (who serve) / long-term inmates (who serve time)" },
  rights: { clue: "Corrects entitlements", how: "Double definition: RIGHTS (corrects) / RIGHTS (entitlements)" },
  girths: { clue: "Cinches or circumferences", how: "Double definition" },
  runway: { clue: "Manage the road to the catwalk", how: "RUN (manage) + WAY (road)" },
  unwary: { clue: "Like a mouse ignoring the cat", how: "Cryptic definition: off guard, like a mouse that ignores the cat" },
  sample: { clue: "Taste from Sam, please", how: "Hidden in SAM PLEase (S-A-M-P-L-E)" },
  maples: { clue: "Chart the French syrup trees", how: "MAP (chart) + LES (the, French)" },
  scored: { clue: "Wrote music and kept count", how: "Double definition: wrote (film) music / kept count" },
  decors: { clue: "Styles found in suede corset", how: "Hidden in sueDE CORSet" },
  coders: { clue: "They write for Java", how: "Cryptic definition: programmers write Java code (not the island or the coffee)" },
  credos: { clue: "Beliefs: about do-overs", how: "C (about) + REDOS (do-overs)" },
  scrape: { clue: "Graze in a tight spot", how: "Double definition: SCRAPE (graze) / SCRAPE (tight spot)" },
  capers: { clue: "Frolics or jobs for crooks", how: "Double definition: CAPERS (frolics) / CAPERS (jobs for crooks)" },
  recaps: { clue: "Summaries about hats", how: "RE (about) + CAPS (hats)" },
  spacer: { clue: "Gap filler in workspace redesign", how: "Hidden in workSPACE Redesign" },
  pacers: { clue: "Anxious walkers on Indiana's team", how: "Double definition: PACERS (anxious walkers) / PACERS (Indiana's team)" },
  scream: { clue: "Yell that's a real riot", how: "Double definition: SCREAM (yell) / SCREAM (a real riot, a hilarious thing)" },
  creams: { clue: "Beats soundly and moisturizes", how: "Double definition: CREAMS (beats soundly) / CREAMS (moisturizes)" },
  search: { clue: "Hunt for in-house architect", how: "Hidden in in-houSE ARCHitect" },
  arches: { clue: "Curves as parades lose their leader", how: "(M)ARCHES: MARCHES (parades) minus its first letter" },
  chaser: { clue: "Follow-up drink in purchase record", how: "Hidden in purCHASE Record" },
  senior: { clue: "Spanish sir swallows one twelfth-grader", how: "SEN(I)OR: I (one) inside SENOR (Spanish sir)" },
  nosier: { clue: "More prying, louder but for one", how: "NOISIER (louder) minus I (one)" },
  serial: { clue: "Episodic breakfast food, aloud", how: "Sounds like CEREAL" },
  sailer: { clue: "Vessel said to be a seaman", how: "Sounds like SAILOR (seaman)" },
  shared: { clue: "Split some cash a redcoat pocketed", how: "Hidden in caSH A REDcoat (S-H-A-R-E-D)" },
  dasher: { clue: "Sprinter on Santa's team", how: "Double definition: DASHER (one who dashes, a sprinter) / DASHER (one of Santa's reindeer)" },
  shovel: { clue: "Push left to dig", how: "SHOVE (push) + L (left)" },
  hovels: { clue: "Digs missing the top are shacks", how: "(s)HOVELS: SHOVELS (digs) minus first letter" },
  shrine: { clue: "Holy place with king in its glow", how: "SH(R)INE: R (king) inside SHINE (glow)" },
  shiner: { clue: "Black eye for a small fish", how: "Double definition: BLACK EYE / SMALL FISH (a minnow)" },
  signal: { clue: "Notice Al's blinker", how: "SIGN (notice) + AL" },
  aligns: { clue: "Lines up headless slanders", how: "(M)ALIGNS: MALIGNS (slanders) minus its head" },
  silver: { clue: "Sterling in utensil, very shiny", how: "Hidden in utenSIL VERy" },
  livers: { clue: "Organs, or people who live", how: "Double definition: LIVERS (organs) / LIVERS (those who live)" },
  sliver: { clue: "Tiny piece of the Beatles' Liverpool", how: "Hidden in beatleS' LIVERpool" },
  slower: { clue: "Seeder planting fifty is less fast", how: "S(L)OWER: L (fifty) inside SOWER (seeder)" },
  lowers: { clue: "Lets down and scowls", how: "Double definition: LOWERS (lets down) / LOWERS (scowls, as in 'lour')" },
  snatch: { clue: "Grab a bit", how: "Double definition: SNATCH (grab) / SNATCH (a bit, as of song)" },
  chants: { clue: "Crowd cries partly make coach antsy", how: "Hidden in coaCH ANTSy" },
  solemn: { clue: "Grave fish from Minnesota", how: "SOLE (fish) + MN (Minnesota)" },
  lemons: { clue: "Sour fruit, or sour deals", how: "Double definition: LEMONS (sour fruit) / LEMONS (bad buys)" },
  melons: { clue: "Honeydews in caramel on sundaes", how: "Hidden in caraMEL ON Sundaes" },
  sought: { clue: "Sally's lead should be pursued", how: "S (Sally's lead) + OUGHT (should)" },
  toughs: { clue: "Toward cries of 'Yuck!' come the thugs", how: "TO (toward) + UGHS (cries of 'Yuck!')" },
  spider: { clue: "Web weaver, or a solitaire game", how: "Double definition" },
  prides: { clue: "Lion groups: quiet trips", how: "P (quiet) + RIDES (trips)" },
  stance: { clue: "Posture seen in first ancestors", how: "Hidden in firST ANCEstors" },
  ascent: { clue: "Rise to agreement, we hear", how: "Sounds like ASSENT (agreement)" },
  stared: { clue: "Looked hard as some vista reddened", how: "Hidden in viSTA REDdened (S-T-A-R-E-D)" },
  trades: { clue: "Swaps occupations", how: "Double definition: trades (swaps) / trades (occupations)" },
  treads: { clue: "Steps: time studies", how: "T (time) + READS (studies)" },
  starve: { clue: "Gawk around five and go hungry", how: "STAR(V)E: V (five) inside STARE (gawk)" },
  averts: { clue: "Prevents warnings, trading fifty for five", how: "ALERTS (warnings) with L (fifty) swapped for V (five)" },
  streak: { clue: "Run of luck or hair highlight", how: "Double definition: STREAK (run of luck) / STREAK (hair highlight)" },
  skater: { clue: "Boarder found in Alaska terrain", how: "Hidden in AlaSKA TERrain (S-K-A-T-E-R)" },
  takers: { clue: "Nameless oil ships find buyers", how: "TA(n)KERS: TANKERS (oil ships) minus N (name)" },
  strike: { clue: "A walkout, or a perfect roll", how: "Double definition: STRIKE (walkout) / STRIKE (all ten pins in bowling)" },
  trikes: { clue: "Attempts to hold a thousand kids' rides", how: "TRI(K)ES: K (thousand) inside TRIES (attempts)" },
  stroke: { clue: "Brain attack or a golf swing", how: "Double definition" },
  stoker: { clue: "Fireman who created Dracula", how: "Double definition: STOKER (fireman) / STOKER (Bram, Dracula's creator)" },
  subtle: { clue: "Caption loses it, being understated", how: "SUBTITLE (caption) minus IT" },
  bustle: { clue: "Rush Victorian dress padding", how: "Double definition: rush / Victorian dress padding" },
  bluest: { clue: "Most down, like the deepest sea", how: "Double definition: most down / most blue (like the deepest sea)" },
  sublet: { clue: "Hero allowed to rent out", how: "SUB (hero) + LET (allowed)" },
  throne: { clue: "Royal seat hurled, by the sound of it", how: "Sounds like THROWN (hurled)" },
  hornet: { clue: "Trumpet greeting Spielberg's alien? A wasp", how: "HORN (trumpet) + ET (Spielberg's alien)" },
  traced: { clue: "Followed the lines; located the caller", how: "Double definition: TRACED (followed the lines, as a drawing) / TRACED (located the caller)" },
  redact: { clue: "Censor: communist law", how: "RED (communist) + ACT (law)" },
  traces: { clue: "Hints seen in boat races", how: "Hidden in boaT RACES" },
  crates: { clue: "Boxes: about prices", how: "C (about) + RATES (prices)" },
  caster: { clue: "Fly fisher on a swivel wheel", how: "Double definition: CASTER (fly fisher, one who casts) / CASTER (swivel wheel)" },
  reacts: { clue: "Responds about deeds", how: "RE (about) + ACTS (deeds)" },
  recast: { clue: "Remake about a plaster mold", how: "RE (about) + CAST (plaster mold)" },
  trance: { clue: "Hint holding new spell", how: "TRA(N)CE: N (new) inside TRACE (hint)" },
  nectar: { clue: "Sweet drink for throat pitch, we hear", how: "Sounds like NECK (throat) + TAR (pitch)" },
  canter: { clue: "Easy gait of a Mexican terrier", how: "Hidden in mexiCAN TERrier" },
  recant: { clue: "Retract about jargon", how: "RE (about) + CANT (jargon)" },
  trials: { clue: "Tough times in court", how: "Double definition: tough times / (proceedings) in court" },
  trails: { clue: "Follows paths", how: "Double definition: follows (v.) / paths (n.)" },
  tribes: { clue: "Clans' tributes, with Utah left out", how: "TRIBUTES minus UT (Utah)" },
  biters: { clue: "Cocktail flavoring, sans tea, for nippers", how: "BIT(T)ERS: BITTERS (cocktail flavoring) minus T (tea)" },
  unable: { clue: "Powerless: \"a\" in Paris, competent", how: "UN (French \"a\") + ABLE (competent)" },
  nebula: { clue: "Star nursery: Nebraska bull, tail docked, and a", how: "NE (Nebraska) + BUL(l) (bull, tail docked) + A" },
  voters: { clue: "They cast, but never fish", how: "Cryptic definition: voters cast ballots, not fishing lines" },
  strove: { clue: "Tried, in part, the latest Rover", how: "Hidden in lateST ROVEr" },
  troves: { clue: "Hoards hiding in retro vests", how: "Hidden in reTRO VESts" },
  waters: { clue: "Seas, or what breaks before a birth", how: "Double definition: seas / what breaks before a birth (her waters broke)" },
  waster: { clue: "Spendthrift in Iowa, stereotypically", how: "Hidden in ioWA STEReotypically" },
  winter: { clue: "Take most of the term in the cold season", how: "WIN (take) + TER(m) (most of the term)" },
  twiner: { clue: "Climber spotted at winery", how: "Hidden in aT WINERy" },
  wolves: { clue: "Pack animals that carry nothing", how: "Cryptic definition: wolves run in packs but are not beasts of burden" },
  vowels: { clue: "Swear by Chicago trains, like A and E", how: "VOW (swear) + ELS (Chicago trains)" },
  wonder: { clue: "Ponder a miracle", how: "Double definition: PONDER / A MIRACLE" },
  downer: { clue: "Blue emergency room's a buzzkill", how: "DOWN (blue) + ER (emergency room)" },
};
