/**
 * One clue per word that can be a clued answer — every word of every
 * family (the generator may clue either member).
 *
 * DRAFTS: written by AI, awaiting a human review pass before launch.
 * Rules for a clue: short (it has two lines above the board at the
 * default text size), plain, no wordplay that needs the anagram trick
 * to parse, and it must never lean on the family's OTHER word — the
 * hidden word is an anagram of every answer here.
 *
 * clues.test.ts asserts every family word has one, so a dictionary
 * change that adds a family fails loudly instead of shipping a blank.
 */
export const CLUES: Readonly<Record<string, string>> = {
  angels: "Winged messengers",
  angles: "Corners measured in degrees",
  begins: "Gets under way",
  beings: "Living creatures",
  brakes: "They stop a car",
  breaks: "Snaps in two",
  burden: "A heavy load to carry",
  burned: "Scorched by fire",
  caring: "Kind and concerned",
  course: "Part of a meal, or of a degree",
  credit: "Recognition for work done",
  danger: "Risk of harm",
  denial: "Refusal to admit the truth",
  depart: "Leave, as a train",
  design: "A plan or drawing",
  direct: "Straight, without detours",
  duties: "Tasks you are bound to do",
  equals: "Is the same as, in a sum",
  escort: "Go along with, for protection",
  forest: "Land thick with trees",
  foster: "Care for a child not your own",
  garden: "Where flowers and vegetables grow",
  groans: "Sounds of pain or complaint",
  hatred: "Intense dislike",
  hostel: "Cheap lodging for travellers",
  hotels: "Places to stay when away",
  ideals: "Standards to live up to",
  ignore: "Pay no attention to",
  insect: "Six-legged creature",
  ladies: "Women, politely",
  learnt: "Picked up a skill",
  lights: "Lamps and bulbs",
  listen: "Pay attention to a sound",
  lowest: "At the very bottom",
  marine: "Of the sea",
  master: "Expert at a craft",
  models: "They pose for photographers",
  nailed: "Fastened with a hammer",
  nicest: "Most pleasant",
  nights: "Hours of darkness",
  organs: "Heart and lungs, for two",
  parted: "Went separate ways",
  patrol: "Guard's round",
  pilots: "They fly planes",
  pistol: "Small handgun",
  plains: "Wide flat grasslands",
  portal: "Doorway to another place",
  racing: "Speeding to win",
  ransom: "Price demanded for a hostage",
  region: "Area of a country",
  remain: "Stay behind",
  rental: "Something you hire, like a car",
  resign: "Quit a job",
  romans: "Citizens of ancient Rome",
  sacred: "Holy",
  sailed: "Crossed the sea by boat",
  scared: "Frightened",
  sector: "A part of the economy",
  seldom: "Not often",
  signed: "Put a name to",
  silent: "Making no sound",
  singer: "Vocalist",
  slight: "Small, or a snub",
  sorted: "Put in order",
  source: "Where something comes from",
  spared: "Let off, mercifully",
  spinal: "Of the backbone",
  spread: "Butter it on toast",
  squeal: "High-pitched cry",
  stable: "Steady, or a home for horses",
  stayed: "Didn't leave",
  steady: "Firm and unshaking",
  stored: "Kept for later",
  strain: "Pull a muscle",
  stream: "Small river",
  struck: "Hit",
  suited: "Well matched",
  tables: "Furniture you eat at",
  things: "Objects",
  thread: "Sewing strand",
  towels: "Bathroom dryers",
  trains: "They run on rails",
  trucks: "Heavy lorries",
  wander: "Roam without aim",
  warden: "Keeper of a prison",
  warned: "Cautioned",
};

export function clueFor(word: string): string {
  return CLUES[word] ?? "";
}
