/**
 * Two or three clues per word that can be a clued answer — every word of
 * every family (the generator may clue either member). A family returns
 * every `families.length` days; each return takes the next clue in its
 * word's list (`clueFor(word, cycle)`), so a returning player doesn't meet
 * the same line twice in a row.
 *
 * DRAFTS: written by AI, awaiting a human review pass before launch.
 *
 * Style is crossword-grade, "cryptic-lite": straight definitions, double
 * definitions, misdirection, and the odd "?" pun or fill-in-the-blank.
 * The rest of the UI stays plain (house copy rule); the clue is the one
 * place wordplay belongs, because the letter pad already gives the
 * answer's letters away — only a clue with some bite is a challenge.
 *
 * Rules every clue keeps (clues.test.ts enforces the checkable ones):
 * - it fits its own word and NOT the family's other words (HOSTEL and
 *   HOTELS each need a clue the other can't answer);
 * - it never contains a family word;
 * - at most 40 characters — two lines on the clue card at Huge text;
 * - American spelling in the clue itself.
 */
export const CLUES: Readonly<Record<string, readonly string[]>> = {
  angels: ["Halo wearers", "Guardians with wings", "Startup backers, informally"],
  angles: ["Corners measured in degrees", "Fishes (for), as compliments", "Viewpoints a photographer picks"],
  begins: ["Gets under way", "Kicks off", "Starts, as a story"],
  beings: ["Living creatures", "Humans and aliens alike", "Existences"],
  brakes: ["They stop a car", "Slows, with a pedal", "Puts a stop to"],
  breaks: ["Snaps in two", "Recesses", "Lucky ___ (good fortune)"],
  burden: ["A heavy load to carry", "Weighs down", "___ of proof"],
  burned: ["Scorched", "Copied onto a CD", "Dissed, informally"],
  caring: ["Kind and concerned", "Nurturing", "Giving a hoot?"],
  racing: ["Speeding to win", "Pounding, as a heart", "Sport of kings, e.g."],
  course: ["Part of a meal, or of a degree", "Golf venue", "Of ___! (naturally)"],
  source: ["Where something comes from", "A river's origin", "Reporter's informant"],
  credit: ["Recognition for work done", "Buy now, pay later", "Line in a film's closing roll"],
  direct: ["Straight, without detours", "Call the shots on set", "Nonstop, as a flight"],
  danger: ["Risk of harm", "Peril", "What a skull and crossbones means"],
  garden: ["Where flowers grow", "Eden, for one", "Lead up the ___ path"],
  denial: ["Refusal to admit the truth", "Not just a river in Egypt?", "Rejection of a request"],
  nailed: ["Fastened with a hammer", "Aced, informally", "Caught red-handed"],
  depart: ["Leave, as a train", "Head out", "Die, euphemistically"],
  parted: ["Went separate ways", "Like the Red Sea, famously", "Combed into two sides, as hair"],
  design: ["A plan or drawing", "Blueprint", "Intend, or sketch"],
  signed: ["Put a name to", "Autographed", "Joined the team, as a free agent"],
  duties: ["Tasks you're bound to do", "Import taxes", "Chores"],
  suited: ["Well matched", "Dressed for the office?", "Right for the job"],
  equals: ["Is the same as", "Peers", "What the = sign says"],
  squeal: ["High-pitched cry", "Rat on someone", "Sound of a pig or a tire"],
  escort: ["Go along with, for protection", "Usher", "Date to the prom, say"],
  sector: ["A part of the economy", "Pie-slice shape, in geometry", "Zone"],
  forest: ["Land thick with trees", "Can't see it for the trees?", "Woods"],
  foster: ["Care for a child not your own", "Encourage, as growth", "Nurture"],
  groans: ["Sounds of pain or complaint", "Reactions to bad puns", "Moans"],
  organs: ["Heart and lungs, for two", "Church instruments", "Mouthpieces, as newspapers"],
  hatred: ["Intense dislike", "Loathing", "Love's opposite"],
  thread: ["Sewing strand", "Chain of replies online", "Needle's partner"],
  hostel: ["Budget bunk-bed lodging", "Backpackers' dorm", "Youth ___"],
  hotels: ["Chain places with room service", "Inns with lobbies", "Places with concierges"],
  ideals: ["Standards to live up to", "Perfect models", "Principles"],
  ladies: ["Women, politely", "___ first!", "Sign on a restroom door"],
  sailed: ["Crossed the sea by boat", "Breezed (through), as an exam", "Went by yacht"],
  ignore: ["Pay no attention to", "Leave on read, say", "Tune out"],
  region: ["Area of a country", "Zone", "Part of the body, anatomically"],
  insect: ["Six-legged creature", "Ant or bee", "Bug"],
  nicest: ["Most pleasant", "Kindest", "Most agreeable"],
  learnt: ["Studied, in London", "Picked up, as a Brit might say", "Mastered, across the pond"],
  rental: ["Something you lease, like a car", "Apartment you don't own", "Car from the airport lot"],
  lights: ["Lamps and bulbs", "Traffic signals", "Ignites"],
  slight: ["Small", "A snub", "Minor, as a chance"],
  listen: ["Pay attention to a sound", "Lend an ear", "Hear out"],
  silent: ["Making no sound", "Like the K in knife", "Mum"],
  lowest: ["At the very bottom", "Rock-bottom", "Cheapest, as a bid"],
  towels: ["Bathroom dryers", "Bath linens", "Things a quitter throws in?"],
  marine: ["Of the sea", "Oceanic", "Leatherneck"],
  remain: ["Stay behind", "Be left over", "Endure"],
  master: ["Expert at a craft", "Original recording", "Lord of the manor"],
  stream: ["Small river", "Watch online, live", "Brook"],
  models: ["They pose for photographers", "Scale replicas", "Makes of car"],
  seldom: ["Not often", "Rarely", "Hardly ever"],
  nights: ["Hours of darkness", "Evenings", "Arabian ___"],
  things: ["Objects", "Stuff", "Stranger ___ (TV show)"],
  patrol: ["Guard's round", "Police beat", "Walk the perimeter"],
  portal: ["Doorway to another place", "Gateway", "Website entry page"],
  pilots: ["They fly planes", "Test episodes of a TV series", "Steers"],
  pistol: ["Small handgun", "Starter's gun", "Lively person, informally"],
  plains: ["Wide flat grasslands", "Prairies", "Great ___ (US region)"],
  spinal: ["Of the backbone", "___ cord", "Vertebral"],
  ransom: ["Price demanded for a hostage", "Kidnapper's demand", "Hold for ___"],
  romans: ["Caesar's people", "Colosseum crowd", "New Testament letter"],
  resign: ["Quit a job", "Step down", "Accept, as one's fate"],
  singer: ["Vocalist", "Choir member", "Soloist at the mic"],
  sacred: ["Holy", "Hallowed", "Like a cow no one may touch?"],
  scared: ["Frightened", "Spooked", "Chicken"],
  spared: ["Let off, mercifully", "Saved from harm", "Did without, as expense"],
  spread: ["What goes on toast", "Ranch, for one", "Unfold, as wings"],
  stable: ["Steady", "Home for horses", "In good condition, medically"],
  tables: ["Furniture you eat at", "Charts of data", "Postpones, as a motion"],
  stayed: ["Didn't leave", "Remained", "Put up for the night"],
  steady: ["Firm and unshaking", "Going ___ (dating)", "Stable"],
  strain: ["Pull a muscle", "Variety of a virus", "Filter, as pasta"],
  trains: ["They run on rails", "Coaches", "Practices, as an athlete"],
  struck: ["Hit", "Went on strike", "Impressed"],
  trucks: ["Big rigs", "Pickups", "Semis"],
  wander: ["Roam without aim", "Stray", "Drift, as a mind"],
  warden: ["Keeper of a prison", "Game ___", "Guardian"],
  warned: ["Cautioned", "Tipped off", "Gave a heads-up"],
  // Promoted families (pool growth, round 3).
  actors: ["Cast members", "They take the stage", "Broadway players"],
  costar: ["Shares top billing", "Fellow lead in a film", "Screen partner"],
  castor: ["___ oil", "Wheel under a sofa leg", "Beaver, in Latin"],
  aliens: ["Visitors from space", "E.T. and friends", "Foreigners, legally"],
  saline: ["Salty", "IV bag solution", "Contact lens rinse"],
  ashore: ["On dry land", "Toward the beach", "Washed up, as driftwood"],
  hoarse: ["Raspy-voiced", "Croaky after a concert", "Like a voice after cheering"],
  badger: ["Pester", "Striped burrower", "Honey ___ (fearless beast)"],
  barged: ["Pushed in rudely", "Burst in uninvited", "Moved like a flat boat?"],
  barely: ["Only just", "Hardly", "By a whisker"],
  barley: ["Grain for beer", "Soup grain", "Pearl ___"],
  bleary: ["Blurry, as tired eyes", "Dim and watery", "Like eyes at 6 a.m."],
  blamed: ["Held responsible", "Pointed a finger at", "Faulted"],
  bedlam: ["Chaos", "Utter uproar", "Pandemonium"],
  boiler: ["Water heater", "Basement furnace", "Steam engine's heart"],
  reboil: ["Heat the kettle again", "Bring back to bubbling", "Warm up, as cold tea"],
  breast: ["Chicken cut", "Stroke in swimming", "Chest"],
  barest: ["Most minimal", "The ___ minimum", "Most exposed"],
  breath: ["Inhale's partner", "Mint freshens it", "Hold it underwater"],
  bather: ["Swimmer at the beach", "Tub user", "One taking a dip"],
  bridal: ["Of a wedding", "___ shower", "Like a veil or gown"],
  ribald: ["Bawdy", "Racy, as humor", "Off-color"],
  bruise: ["Black-and-blue mark", "Hurt a peach", "Contusion"],
  buries: ["Covers with dirt", "Hides, like a dog's bone", "Lays to rest"],
  busier: ["More hectic", "Having more on one's plate", "Less idle"],
  rubies: ["Red gems", "July birthstones", "Dorothy's slippers had them"],
  busted: ["Caught red-handed", "Broken", "Arrested, slangily"],
  debuts: ["First appearances", "Premieres", "Coming-out parties"],
  buster: ["Myth ___s (TV)", "Dam ___ (bomber)", "Pal, gruffly"],
  brutes: ["Thugs", "Savage beasts", "Bullies"],
  tubers: ["Potatoes, e.g.", "Root vegetables", "Yams and taros"],
  rebuts: ["Argues against", "Counters, in a debate", "Refutes"],
  candle: ["Wax light", "Birthday cake topper", "Can't hold a ___ to"],
  lanced: ["Pierced", "Drained, as a boil", "Speared, as a knight"],
  cartel: ["Price-fixing ring", "Drug syndicate", "OPEC, for one"],
  claret: ["Red Bordeaux", "Wine red", "Dark red color"],
  castle: ["Fortress", "Rook's move in chess", "A home is one, they say"],
  cleats: ["Soccer shoes", "Spiked sports footwear", "Rope fittings on a dock"],
  chains: ["Links", "Bike parts", "Store groups like Target"],
  chinas: ["Fine dinnerwares", "Porcelain sets", "Cockney mates"],
  charts: ["Graphs", "Top 40 lists", "Maps for sailors"],
  starch: ["Collar stiffener", "Potato carb", "Laundry spray"],
  cinema: ["Movie theater", "Film art", "Where the popcorn is"],
  anemic: ["Iron-deficient", "Weak, as sales", "Pale and feeble"],
  iceman: ["Ice deliverer of old", "Top Gun pilot", "One who's cool under pressure"],
  clears: ["Removes", "Acquits", "Jumps over, as a hurdle"],
  scaler: ["Fish-cleaning tool", "Dental tool", "Mountain climber"],
  cursed: ["Swore", "Hexed", "Under a spell"],
  crudes: ["Unrefined oils", "Oil-market grades", "Brent and WTI"],
  dancer: ["Ballerina", "One of Santa's reindeer", "Tapper or twirler"],
  craned: ["Stretched one's neck", "Lifted by derrick", "Peered over the crowd"],
  dances: ["Proms", "Waltzes and tangos", "Moves to music"],
  ascend: ["Climb", "Rise", "Go up"],
  deacon: ["Church officer", "Minister's assistant", "Parish helper"],
  canoed: ["Paddled", "Went down a river", "Traveled by kayak's cousin"],
  debris: ["Rubble", "Wreckage", "Space junk"],
  brides: ["Veil wearers", "Newlyweds, often", "Wedding stars"],
  detail: ["Fine point", "Car wash service", "Bodyguard unit"],
  dilate: ["Widen, as pupils", "Expand", "Open up, as a vessel"],
  tailed: ["Followed", "Shadowed", "Long-___ comet"],
  detour: ["Roundabout route", "Road-work sign", "Alternate path"],
  routed: ["Crushed in battle", "Sent a set way", "Beaten badly"],
  toured: ["Went on the road", "Sightsaw", "Played many venues"],
  diaper: ["Baby's garment", "Pampers item", "Nappy, stateside"],
  paired: ["Matched up", "Twinned", "Coupled"],
  repaid: ["Paid back", "Returned the favor", "Settled a loan"],
  donate: ["Give", "Contribute", "Give to charity"],
  atoned: ["Made amends", "Paid for one's sins", "Said sorry, in deed"],
  drives: ["Road trips", "Motivations", "Golf shots off tees"],
  divers: ["Scuba fans", "Olympic poolside athletes", "Pearl hunters"],
  drones: ["Male bees", "Buzzing aircraft", "Monotonous hums"],
  snored: ["Sawed logs", "Slept noisily", "Rattled the room"],
  editor: ["Magazine boss", "Red-pen wielder", "Film cutter"],
  rioted: ["Ran wild in the streets", "Revolted", "Rampaged"],
  triode: ["Vacuum tube", "Old amplifier part", "Three-electrode tube"],
  failed: ["Flunked", "Didn't pass", "Went under, as a business"],
  afield: ["Far away", "Far ___", "Off the beaten path"],
  faster: ["Quicker", "Speedier", "More like a hare"],
  strafe: ["Machine-gun from the air", "Shoot while sidestepping", "Rake with fire"],
  filter: ["Coffee paper", "Instagram effect", "Strain"],
  lifter: ["Weight trainer", "Face-___", "Jack for a car"],
  trifle: ["Layered dessert", "Small matter", "Toy (with)"],
  finest: ["Best", "Top-quality", "New York's ___ (police)"],
  infest: ["Overrun, as pests", "Swarm", "Plague"],
  finger: ["Digit", "Point out", "Ring holder"],
  fringe: ["Edge", "Lunatic ___", "Tassel trim"],
  forces: ["Armed services", "Compels", "Gravity and friction"],
  fresco: ["Wall painting", "Sistine ceiling art", "Al ___ (outdoors)"],
  formed: ["Shaped", "Created", "Took shape"],
  deform: ["Warp", "Misshape", "Twist out of shape"],
  freaks: ["Oddballs", "Fanatics", "___ out (panics)"],
  fakers: ["Pretenders", "Phonies", "Frauds"],
  friend: ["Pal", "Buddy", "Facebook connection"],
  finder: ["___'s fee", "Lost-and-found hero", "Locator"],
  gifted: ["Talented", "Presented", "Precocious"],
  fidget: ["Squirm", "___ spinner", "Can't sit still"],
  golden: ["Gilded", "___ retriever", "Anniversary number 50"],
  longed: ["Yearned", "Pined", "Ached (for)"],
  grapes: ["Vine fruit", "Wine source", "Sour ___"],
  pagers: ["Beepers", "'90s doctor gadgets", "Buzzers on belts"],
  grunts: ["Pig noises", "Foot soldiers", "Lifting sounds"],
  strung: ["Like a guitar", "___ out (exhausted)", "Threaded, as beads"],
  hearts: ["Card suit", "Valentine shapes", "Love, in emoji"],
  earths: ["Planets like ours", "Soils", "Grounds, electrically"],
  haters: ["Critics online", "Gonna hate, per Swift", "Detractors"],
  hustle: ["Hurry", "Side gig", "Con game"],
  sleuth: ["Detective", "Private eye", "Sherlock, e.g."],
  images: ["Pictures", "Photos", "Reflections"],
  ageism: ["Bias against the old", "Bias by birth year", "Workplace bias against seniors"],
  inches: ["Ruler units", "Creeps (along)", "Twelve per foot"],
  niches: ["Wall nooks", "Specialties", "Market segments"],
  insult: ["Put-down", "Dis", "Offend"],
  sunlit: ["Bright with rays", "Lit by day", "Like a sunroom"],
  itself: ["By ___ (alone)", "In and of ___", "Its own self"],
  stifle: ["Suppress", "Smother", "Hold back, as a yawn"],
  filets: ["Boneless cuts", "Mignon cuts", "Fish slices"],
  lasted: ["Endured", "Held up", "Went the distance"],
  deltas: ["River mouths", "Greek D's", "Changes, in math"],
  layers: ["Cake tiers", "Hens", "An onion's parts"],
  relays: ["Races with batons", "Passes along", "Electrical switches"],
  slayer: ["Dragon killer", "Buffy's title", "Killer"],
  layout: ["Floor plan", "Page design", "Arrangement"],
  outlay: ["Expense", "Spending", "Cost"],
  linked: ["Connected", "Joined", "Chained"],
  kindle: ["Ignite", "E-reader", "Spark"],
  listed: ["Itemized", "Leaned, as a ship", "On the menu"],
  delist: ["Remove from the exchange", "Take off the register", "Unregister"],
  locker: ["Gym storage", "Davy Jones's ___", "School hallway box"],
  relock: ["Secure again", "Bolt once more", "Lock again"],
  lovers: ["Romeo and Juliet", "Sweethearts", "Fans (of)"],
  solver: ["Puzzle whiz", "Problem cracker", "Crossword fan"],
  maiden: ["Unmarried girl", "First, as a voyage", "Iron ___"],
  median: ["Middle value", "Highway strip", "Midpoint"],
  marble: ["Statue stone", "Kid's glass ball", "Lost one's ___s"],
  ramble: ["Wander", "Talk on and on", "Stroll"],
  medals: ["Olympic prizes", "Golds and silvers", "Military honors"],
  damsel: ["___ in distress", "Young lady of old", "Fair maiden, poetically"],
  mental: ["Of the mind", "Cerebral", "Crazy, slangily"],
  lament: ["Mourn", "Dirge", "Wail over"],
  mantle: ["Cloak", "Earth layer", "Take up the ___"],
  minute: ["Tiny", "Sixty seconds", "Meeting record"],
  minuet: ["Stately dance", "Mozart dance form", "Baroque step"],
  mister: ["Mr.", "Sir, informally", "Spray bottle"],
  merits: ["Deserves", "Virtues", "Scout badge type"],
  timers: ["Egg ___", "Kitchen clocks", "Countdown devices"],
  remits: ["Sends payment", "Pardons", "Areas of authority"],
  morals: ["Ethics", "Fable lessons", "Principles"],
  molars: ["Back teeth", "Grinders", "Wisdom teeth, e.g."],
  neural: ["Of nerves", "___ network", "Brain-related"],
  unreal: ["Incredible", "Fake", "Dreamlike"],
  novels: ["Books", "Fiction works", "New things?"],
  sloven: ["Slob", "Messy person", "Untidy one"],
  oceans: ["Seas", "Five big waters", "Heaps"],
  canoes: ["Paddled boats", "Kayak cousins", "Dugouts"],
  ordeal: ["Trial", "Rough experience", "Nightmare"],
  loader: ["Forklift, e.g.", "Dishwasher filler", "Front-end ___"],
  reload: ["Refresh, as a page", "Add more ammo", "F5, in a browser"],
  others: ["The rest", "Everyone else", "Different ones"],
  throes: ["Death ___", "In the ___ of", "Violent spasms"],
  owners: ["Proprietors", "Holders", "Deed holders"],
  worsen: ["Deteriorate", "Go downhill", "Aggravate"],
  parcel: ["Package", "Lot of land", "Part and ___"],
  placer: ["Gold deposit", "Top-three finisher", "One who places"],
  parent: ["Mom or dad", "Guardian", "Raise, as a child"],
  entrap: ["Snare", "Catch by trickery", "Sting, like cops"],
  partly: ["In part", "Somewhat", "Not fully"],
  paltry: ["Meager", "Measly", "Trifling"],
  patron: ["Regular customer", "Sponsor", "___ saint"],
  tarpon: ["Big game fish", "Silver king fish", "Florida sport fish"],
  planes: ["Aircraft", "Flat surfaces", "Woodworking tools"],
  panels: ["Solar ___", "Discussion groups", "Door sections"],
  planet: ["World", "Mars, e.g.", "Captain ___"],
  platen: ["Typewriter roller", "Press plate", "Printer's flat plate"],
  plates: ["Dishes", "License ___", "Tectonic pieces"],
  staple: ["Office fastener", "Dietary basic", "Rice, in many diets"],
  petals: ["Daisy parts", "Rose parts", "Flower-girl tosses"],
  pastel: ["Soft color", "Chalky crayon", "Baby blue, e.g."],
  pleats: ["Skirt folds", "Kilt creases", "Accordion folds"],
  palest: ["Most wan", "Whitest", "Least tanned"],
  player: ["Gamer", "Athlete", "Casanova"],
  replay: ["Instant ___", "Rerun", "Watch again"],
  pearly: ["___ gates", "___ whites (teeth)", "Lustrous"],
  posted: ["Mailed", "Shared online", "Stationed"],
  depots: ["Bus stations", "Warehouses", "Train stops"],
  despot: ["Tyrant", "Dictator", "Autocrat"],
  poster: ["Wall hanging", "Movie ad", "Forum user"],
  presto: ["Magician's word", "Very fast, musically", "Hey ___!"],
  tropes: ["Clichés", "Figures of speech", "Story conventions"],
  praise: ["Compliment", "Acclaim", "Laud"],
  aspire: ["Aim high", "Hope to be", "Strive (toward)"],
  priest: ["Clergyman", "Father", "Confessional listener"],
  stripe: ["Zebra line", "Chevron", "Sort, kind"],
  sprite: ["Fairy", "Pixie", "Lemon-lime soda"],
  ripest: ["Most mature, as fruit", "Readiest to pick", "Juiciest"],
  prince: ["Heir", "Royal son", "Purple Rain singer"],
  pincer: ["Crab claw", "___ movement", "Pinching tool"],
  prints: ["Photos", "Publishes", "Lithographs"],
  sprint: ["Dash", "Run fast", "100-meter race"],
  remind: ["Jog the memory", "Nudge", "Prompt"],
  minder: ["Babysitter", "Bodyguard", "Watcher"],
  result: ["Outcome", "Score", "Consequence"],
  luster: ["Shine", "Sheen", "Glow"],
  rustle: ["Leafy sound", "Steal cattle", "___ up (gather)"],
  retain: ["Keep", "Hold on to", "Hire, as a lawyer"],
  retina: ["Eye lining", "Scan for ID", "Light-sensing layer"],
  rifles: ["Guns", "Rummages", "Searches hastily"],
  fliers: ["Leaflets", "Pilots", "Frequent ___"],
  lifers: ["Long-term inmates", "Career soldiers", "Stayers for good"],
  rights: ["Bill of ___", "Entitlements", "Corrects"],
  girths: ["Saddle straps", "Waistlines", "Circumferences"],
  runway: ["Catwalk", "Airstrip", "Fashion show stage"],
  unwary: ["Careless", "Off guard", "Unsuspecting"],
  sample: ["Taste", "Specimen", "Free taste"],
  maples: ["Syrup trees", "Canadian leaves", "Sugar trees"],
  scored: ["Tallied", "Won points", "Etched"],
  decors: ["Interior styles", "Room looks", "Stage settings"],
  coders: ["Programmers", "Devs", "Software writers"],
  credos: ["Beliefs", "Mottos", "Creeds"],
  scrape: ["Graze", "Tight spot", "Scratch"],
  capers: ["Heists", "Pickled buds", "Antics"],
  recaps: ["Summaries", "TV \"previously on\" bits", "Rundowns"],
  spacer: ["Gap filler", "Tile gap piece", "Keyboard bar?"],
  pacers: ["Race rabbits", "Indiana NBA team", "Runners who set speed"],
  scream: ["Yell", "Munch painting", "Horror film shriek"],
  creams: ["Lotions", "Dairy toppings", "Beats soundly"],
  search: ["Look for", "Hunt", "Google, say"],
  arches: ["Doorway curves", "Foot parts", "McDonald's logo"],
  chaser: ["Drink after a shot", "Storm ___", "Pursuer"],
  senior: ["Twelfth-grader", "Elder", "Sr."],
  nosier: ["More prying", "Snoopier", "More intrusive"],
  serial: ["Podcast format", "Cereal's sound-alike", "In a series"],
  sailer: ["Ship, by speed", "Vessel", "Boat, as described by pace"],
  shared: ["Split", "Posted, like a meme", "Divided"],
  dasher: ["Reindeer", "Churn plunger", "Food delivery driver"],
  shovel: ["Spade", "Dig", "Snow tool"],
  hovels: ["Shacks", "Huts", "Shanties"],
  shrine: ["Holy place", "Altar", "Memorial"],
  shiner: ["Black eye", "Bootblack", "Minnow"],
  signal: ["Sign", "Blinker", "Cell bars"],
  aligns: ["Lines up", "Straightens", "Sides (with)"],
  silver: ["Second place", "Argent", "Cutlery"],
  livers: ["Organs", "Foie gras source", "Pâté base"],
  sliver: ["Splinter", "Thin slice", "Shard"],
  slower: ["Less fast", "More like a snail", "Reduced speed"],
  lowers: ["Drops", "Reduces", "Frowns"],
  snatch: ["Grab", "Seize", "Nab"],
  chants: ["Crowd cheers", "Gregorian songs", "Mantras"],
  solemn: ["Grave", "Serious", "Somber"],
  lemons: ["Duds, as cars", "Citrus", "Sour fruit"],
  melons: ["Cantaloupes", "Honeydews", "Big summer fruits"],
  sought: ["Looked for", "Pursued", "In demand"],
  toughs: ["Thugs", "Hoods", "Bullies"],
  spider: ["Web spinner", "Arachnid", "Eight-legged critter"],
  prides: ["Lion groups", "Self-respects", "Parades"],
  stance: ["Position", "Posture", "Viewpoint"],
  ascent: ["Climb", "Rise", "Upward path"],
  stared: ["Gawked", "Gazed", "Ogled"],
  trades: ["Swaps", "Jobs", "Deals"],
  treads: ["Tire grooves", "Steps", "Walks"],
  starve: ["Go hungry", "Famish", "Deprive of food"],
  averts: ["Turns away", "Prevents", "Wards off"],
  streak: ["Run", "Stripe", "Winning run"],
  skater: ["Rink athlete", "Boarder", "Tony Hawk, for one"],
  takers: ["Buyers", "Accepters", "Offer ___"],
  strike: ["Hit", "Walkout", "Bowling feat"],
  trikes: ["Tricycles", "Kid's three-wheelers", "Three-wheel bikes"],
  stroke: ["Swim style", "Caress", "Pen line"],
  stoker: ["Fire feeder", "Dracula's author", "Boiler worker"],
  subtle: ["Faint", "Understated", "Nuanced"],
  bustle: ["Hustle and ___", "Dress padding", "Busy activity"],
  bluest: ["Saddest", "Most azure", "Deepest blue"],
  sublet: ["Rent out", "Sublease", "Rent again"],
  throne: ["Royal seat", "Crown's seat", "King's chair"],
  hornet: ["Stinger", "Wasp", "Buzzer with a sting"],
  traced: ["Copied", "Tracked", "Outlined"],
  redact: ["Black out", "Censor", "Edit out"],
  traces: ["Tracks", "Hints", "Remnants"],
  crates: ["Boxes", "Moving boxes", "Dog carriers"],
  caster: ["Furniture wheel", "Spell-___", "Fishing-line thrower"],
  reacts: ["Responds", "Answers", "Emoji-responds"],
  recast: ["Reshape", "Remake", "Replace actors"],
  trance: ["Daze", "Hypnotic state", "Stupor"],
  nectar: ["Bee food", "Sweet liquid", "Drink of gods"],
  canter: ["Gallop's cousin", "Easy gait", "Horse's run"],
  recant: ["Take back", "Retract", "Disavow"],
  trials: ["Tests", "Hardships", "Courts' proceedings"],
  trails: ["Paths", "Hikes", "Follows"],
  tribes: ["Clans", "Groups", "Peoples"],
  biters: ["Nippers", "Mosquitoes", "Snappers"],
  unable: ["Can't", "Incapable", "Not up to"],
  nebula: ["Star cloud", "Gas cloud", "Cosmic dust"],
  voters: ["Electors", "Poll-goers", "Citizens at the ballot"],
  strove: ["Tried", "Endeavored", "Struggled"],
  troves: ["Hoards", "Treasures", "Caches"],
  waters: ["Irrigates", "Territorial seas", "Seas"],
  waster: ["Squanderer", "Wastrel", "Good-for-nothing"],
  winter: ["Cold season", "Snow season", "December to March"],
  twiner: ["Climbing vine", "Clinger", "Coiler"],
  wolves: ["Pack animals", "Predators", "Howlers"],
  vowels: ["A, E, I, O, U", "Wheel of Fortune buys", "Letters to buy"],
  wonder: ["Marvel", "Awe", "Ponder"],
  downer: ["Buzzkill", "Depressant", "Bummer"],
};

/** The clue for `word` on a family's `cycle`-th return. */
export function clueFor(word: string, cycle = 0): string {
  const list = CLUES[word];
  if (!list?.length) return "";
  return list[((cycle % list.length) + list.length) % list.length];
}
