/**
 * Two STRAIGHT clues per answer word — every word of every family (the
 * generator may clue either member). Each word's third clue is a true
 * cryptic, kept in cryptic.ts; `clueFor` rotates through all three, one
 * per return of the family, so a repeat day never shows the last clue.
 *
 * DRAFTS: written by AI, awaiting a human review pass before launch.
 *
 * Straight clues are crossword-mini style: definitions, the odd
 * fill-in-the-blank or "?" pun. The bite lives in the cryptics. The rest of
 * the UI stays plain (house copy rule).
 *
 * Rules every clue keeps (clues.test.ts enforces the checkable ones):
 * - it fits its own word and NOT the family's other words (HOSTEL and
 *   HOTELS each need a clue the other can't answer);
 * - it never contains a family word;
 * - at most 40 characters (48 for a cryptic) — the clue card's budget;
 * - American spelling in the clue itself.
 */
import { CRYPTIC } from "./cryptic";

export const CLUES: Readonly<Record<string, readonly string[]>> = {
  angels: ["Halo wearers", "Guardians with wings"],
  angles: ["Corners measured in degrees", "Fishes (for), as compliments"],
  begins: ["Gets under way", "Kicks off"],
  beings: ["Living creatures", "Humans and aliens alike"],
  brakes: ["They stop a car", "Slows, with a pedal"],
  breaks: ["Snaps in two", "Recesses"],
  burden: ["A heavy load to carry", "Weighs down"],
  burned: ["Scorched", "Copied onto a CD"],
  caring: ["Kind and concerned", "Nurturing"],
  racing: ["Speeding to win", "Pounding, as a heart"],
  course: ["Part of a meal, or of a degree", "Golf venue"],
  source: ["Where something comes from", "A river's origin"],
  credit: ["Recognition for work done", "Buy now, pay later"],
  direct: ["Straight, without detours", "Call the shots on set"],
  danger: ["Risk of harm", "Peril"],
  garden: ["Where flowers grow", "Eden, for one"],
  denial: ["Refusal to admit the truth", "Not just a river in Egypt?"],
  nailed: ["Fastened with a hammer", "Aced, informally"],
  depart: ["Leave, as a train", "Head out"],
  parted: ["Went separate ways", "Like the Red Sea, famously"],
  design: ["A plan or drawing", "Blueprint"],
  signed: ["Put a name to", "Autographed"],
  duties: ["Tasks you're bound to do", "Import taxes"],
  suited: ["Well matched", "Dressed for the office?"],
  equals: ["Is the same as", "Peers"],
  squeal: ["High-pitched cry", "Rat on someone"],
  escort: ["Go along with, for protection", "Usher"],
  sector: ["A part of the economy", "Pie-slice shape, in geometry"],
  forest: ["Land thick with trees", "Can't see it for the trees?"],
  foster: ["Care for a child not your own", "Encourage, as growth"],
  groans: ["Sounds of pain or complaint", "Reactions to bad puns"],
  organs: ["Heart and lungs, for two", "Church instruments"],
  hatred: ["Intense dislike", "Loathing"],
  thread: ["Sewing strand", "Chain of replies online"],
  hostel: ["Budget bunk-bed lodging", "Backpackers' dorm"],
  hotels: ["Chain places with room service", "Inns with lobbies"],
  ideals: ["Standards to live up to", "Perfect models"],
  ladies: ["Women, politely", "___ first!"],
  sailed: ["Crossed the sea by boat", "Breezed (through), as an exam"],
  ignore: ["Pay no attention to", "Leave on read, say"],
  region: ["Area of a country", "Zone"],
  insect: ["Six-legged creature", "Ant or bee"],
  nicest: ["Most pleasant", "Kindest"],
  learnt: ["Studied, in London", "Picked up, as a Brit might say"],
  rental: ["Something you lease, like a car", "Apartment you don't own"],
  lights: ["Lamps and bulbs", "Traffic signals"],
  slight: ["Small", "A snub"],
  listen: ["Pay attention to a sound", "Lend an ear"],
  silent: ["Making no sound", "Like the K in knife"],
  lowest: ["At the very bottom", "Rock-bottom"],
  towels: ["Bathroom dryers", "Bath linens"],
  marine: ["Of the sea", "Oceanic"],
  remain: ["Stay behind", "Be left over"],
  master: ["Expert at a craft", "Original recording"],
  stream: ["Small river", "Watch online, live"],
  models: ["They pose for photographers", "Scale replicas"],
  seldom: ["Not often", "Rarely"],
  nights: ["Hours of darkness", "Evenings"],
  things: ["Objects", "Stuff"],
  patrol: ["Guard's round", "Police beat"],
  portal: ["Doorway to another place", "Gateway"],
  pilots: ["They fly planes", "Test episodes of a TV series"],
  pistol: ["Small handgun", "Starter's gun"],
  plains: ["Wide flat grasslands", "Prairies"],
  spinal: ["Of the backbone", "___ cord"],
  ransom: ["Price demanded for a hostage", "Kidnapper's demand"],
  romans: ["Caesar's people", "Colosseum crowd"],
  resign: ["Quit a job", "Step down"],
  singer: ["Vocalist", "Choir member"],
  sacred: ["Holy", "Hallowed"],
  scared: ["Frightened", "Spooked"],
  spared: ["Let off, mercifully", "Saved from harm"],
  spread: ["What goes on toast", "Ranch, for one"],
  stable: ["Steady", "Home for horses"],
  tables: ["Furniture you eat at", "Charts of data"],
  stayed: ["Didn't leave", "Remained"],
  steady: ["Firm and unshaking", "Going ___ (dating)"],
  strain: ["Pull a muscle", "Variety of a virus"],
  trains: ["They run on rails", "Coaches"],
  struck: ["Hit", "Went on strike"],
  trucks: ["Big rigs", "Pickups"],
  wander: ["Roam without aim", "Stray"],
  warden: ["Keeper of a prison", "Game ___"],
  warned: ["Cautioned", "Tipped off"],
  // Promoted families (pool growth, round 3).
  actors: ["Cast members", "They take the stage"],
  costar: ["Shares top billing", "Fellow lead in a film"],
  castor: ["___ oil", "Wheel under a sofa leg"],
  aliens: ["Visitors from space", "E.T. and friends"],
  saline: ["Salty", "IV bag solution"],
  ashore: ["On dry land", "Toward the beach"],
  hoarse: ["Raspy-voiced", "Croaky after a concert"],
  badger: ["Pester", "Striped burrower"],
  barged: ["Pushed in rudely", "Burst in uninvited"],
  barely: ["Only just", "Hardly"],
  barley: ["Grain for beer", "Soup grain"],
  bleary: ["Blurry, as tired eyes", "Dim and watery"],
  blamed: ["Held responsible", "Pointed a finger at"],
  bedlam: ["Chaos", "Utter uproar"],
  boiler: ["Water heater", "Basement furnace"],
  reboil: ["Heat the kettle again", "Bring back to bubbling"],
  breast: ["Chicken cut", "Stroke in swimming"],
  barest: ["Most minimal", "The ___ minimum"],
  breath: ["Inhale's partner", "Mint freshens it"],
  bather: ["Swimmer at the beach", "Tub user"],
  bridal: ["Of a wedding", "___ shower"],
  ribald: ["Bawdy", "Racy, as humor"],
  bruise: ["Black-and-blue mark", "Hurt a peach"],
  buries: ["Covers with dirt", "Hides, like a dog's bone"],
  busier: ["More hectic", "Having more on one's plate"],
  rubies: ["Red gems", "July birthstones"],
  busted: ["Caught red-handed", "Broken"],
  debuts: ["First appearances", "Premieres"],
  buster: ["Myth ___s (TV)", "Dam ___ (bomber)"],
  brutes: ["Thugs", "Savage beasts"],
  tubers: ["Potatoes, e.g.", "Root vegetables"],
  rebuts: ["Argues against", "Counters, in a debate"],
  candle: ["Wax light", "Birthday cake topper"],
  lanced: ["Pierced", "Drained, as a boil"],
  cartel: ["Price-fixing ring", "Drug syndicate"],
  claret: ["Red Bordeaux", "Wine red"],
  castle: ["Fortress", "Rook's move in chess"],
  cleats: ["Soccer shoes", "Spiked sports footwear"],
  chains: ["Links", "Bike parts"],
  chinas: ["Fine dinnerwares", "Porcelain sets"],
  charts: ["Graphs", "Top 40 lists"],
  starch: ["Collar stiffener", "Potato carb"],
  cinema: ["Movie theater", "Film art"],
  anemic: ["Iron-deficient", "Weak, as sales"],
  iceman: ["Ice deliverer of old", "Top Gun pilot"],
  clears: ["Removes", "Acquits"],
  scaler: ["Fish-cleaning tool", "Dental tool"],
  cursed: ["Swore", "Hexed"],
  crudes: ["Unrefined oils", "Oil-market grades"],
  dancer: ["Ballerina", "One of Santa's reindeer"],
  craned: ["Stretched one's neck", "Lifted by derrick"],
  dances: ["Proms", "Waltzes and tangos"],
  ascend: ["Climb", "Rise"],
  deacon: ["Church officer", "Minister's assistant"],
  canoed: ["Paddled", "Went down a river"],
  debris: ["Rubble", "Wreckage"],
  brides: ["Veil wearers", "Newlyweds, often"],
  detail: ["Fine point", "Car wash service"],
  dilate: ["Widen, as pupils", "Expand"],
  tailed: ["Followed", "Shadowed"],
  detour: ["Roundabout route", "Road-work sign"],
  routed: ["Crushed in battle", "Sent a set way"],
  toured: ["Went on the road", "Sightsaw"],
  diaper: ["Baby's garment", "Pampers item"],
  paired: ["Matched up", "Twinned"],
  repaid: ["Paid back", "Returned the favor"],
  donate: ["Give", "Contribute"],
  atoned: ["Made amends", "Paid for one's sins"],
  drives: ["Road trips", "Motivations"],
  divers: ["Scuba fans", "Olympic poolside athletes"],
  drones: ["Male bees", "Buzzing aircraft"],
  snored: ["Sawed logs", "Slept noisily"],
  editor: ["Magazine boss", "Red-pen wielder"],
  rioted: ["Ran wild in the streets", "Revolted"],
  triode: ["Vacuum tube", "Old amplifier part"],
  failed: ["Flunked", "Didn't pass"],
  afield: ["Far away", "Far ___"],
  faster: ["Quicker", "Speedier"],
  strafe: ["Machine-gun from the air", "Shoot while sidestepping"],
  filter: ["Coffee paper", "Instagram effect"],
  lifter: ["Weight trainer", "Face-___"],
  trifle: ["Layered dessert", "Small matter"],
  finest: ["Best", "Top-quality"],
  infest: ["Overrun, as pests", "Swarm"],
  finger: ["Digit", "Point out"],
  fringe: ["Edge", "Lunatic ___"],
  forces: ["Armed services", "Compels"],
  fresco: ["Wall painting", "Sistine ceiling art"],
  formed: ["Shaped", "Created"],
  deform: ["Warp", "Misshape"],
  freaks: ["Oddballs", "Fanatics"],
  fakers: ["Pretenders", "Phonies"],
  friend: ["Pal", "Buddy"],
  finder: ["___'s fee", "Lost-and-found hero"],
  gifted: ["Talented", "Presented"],
  fidget: ["Squirm", "___ spinner"],
  golden: ["Gilded", "___ retriever"],
  longed: ["Yearned", "Pined"],
  grapes: ["Vine fruit", "Wine source"],
  pagers: ["Beepers", "'90s doctor gadgets"],
  grunts: ["Pig noises", "Foot soldiers"],
  strung: ["Like a guitar", "___ out (exhausted)"],
  hearts: ["Card suit", "Valentine shapes"],
  earths: ["Planets like ours", "Soils"],
  haters: ["Critics online", "Gonna hate, per Swift"],
  hustle: ["Hurry", "Side gig"],
  sleuth: ["Detective", "Private eye"],
  images: ["Pictures", "Photos"],
  ageism: ["Bias against the old", "Bias by birth year"],
  inches: ["Ruler units", "Creeps (along)"],
  niches: ["Wall nooks", "Specialties"],
  insult: ["Put-down", "Dis"],
  sunlit: ["Bright with rays", "Lit by day"],
  itself: ["By ___ (alone)", "In and of ___"],
  stifle: ["Suppress", "Smother"],
  filets: ["Boneless cuts", "Mignon cuts"],
  lasted: ["Endured", "Held up"],
  deltas: ["River mouths", "Greek D's"],
  layers: ["Cake tiers", "Hens"],
  relays: ["Races with batons", "Passes along"],
  slayer: ["Dragon killer", "Buffy's title"],
  layout: ["Floor plan", "Page design"],
  outlay: ["Expense", "Spending"],
  linked: ["Connected", "Joined"],
  kindle: ["Ignite", "E-reader"],
  listed: ["Itemized", "Leaned, as a ship"],
  delist: ["Remove from the exchange", "Take off the register"],
  locker: ["Gym storage", "Davy Jones's ___"],
  relock: ["Secure again", "Bolt once more"],
  lovers: ["Romeo and Juliet", "Sweethearts"],
  solver: ["Puzzle whiz", "Problem cracker"],
  maiden: ["Unmarried girl", "First, as a voyage"],
  median: ["Middle value", "Highway strip"],
  marble: ["Statue stone", "Kid's glass ball"],
  ramble: ["Wander", "Talk on and on"],
  medals: ["Olympic prizes", "Golds and silvers"],
  damsel: ["___ in distress", "Young lady of old"],
  mental: ["Of the mind", "Cerebral"],
  lament: ["Mourn", "Dirge"],
  mantle: ["Cloak", "Earth layer"],
  minute: ["Tiny", "Sixty seconds"],
  minuet: ["Stately dance", "Mozart dance form"],
  mister: ["Mr.", "Sir, informally"],
  merits: ["Deserves", "Virtues"],
  timers: ["Egg ___", "Kitchen clocks"],
  remits: ["Sends payment", "Pardons"],
  morals: ["Ethics", "Fable lessons"],
  molars: ["Back teeth", "Grinders"],
  neural: ["Of nerves", "___ network"],
  unreal: ["Incredible", "Fake"],
  novels: ["Books", "Fiction works"],
  sloven: ["Slob", "Messy person"],
  oceans: ["Seas", "Five big waters"],
  canoes: ["Paddled boats", "Kayak cousins"],
  ordeal: ["Trial", "Rough experience"],
  loader: ["Forklift, e.g.", "Dishwasher filler"],
  reload: ["Refresh, as a page", "Add more ammo"],
  others: ["The rest", "Everyone else"],
  throes: ["Death ___", "In the ___ of"],
  owners: ["Proprietors", "Holders"],
  worsen: ["Deteriorate", "Go downhill"],
  parcel: ["Package", "Lot of land"],
  placer: ["Gold deposit", "Top-three finisher"],
  parent: ["Mom or dad", "Guardian"],
  entrap: ["Snare", "Catch by trickery"],
  partly: ["In part", "Somewhat"],
  paltry: ["Meager", "Measly"],
  patron: ["Regular customer", "Sponsor"],
  tarpon: ["Big game fish", "Silver king fish"],
  planes: ["Aircraft", "Flat surfaces"],
  panels: ["Solar ___", "Discussion groups"],
  planet: ["World", "Mars, e.g."],
  platen: ["Typewriter roller", "Press plate"],
  plates: ["Dishes", "License ___"],
  staple: ["Office fastener", "Dietary basic"],
  petals: ["Daisy parts", "Rose parts"],
  pastel: ["Soft color", "Chalky crayon"],
  pleats: ["Skirt folds", "Kilt creases"],
  palest: ["Most wan", "Whitest"],
  player: ["Gamer", "Athlete"],
  replay: ["Instant ___", "Rerun"],
  pearly: ["___ gates", "___ whites (teeth)"],
  posted: ["Mailed", "Shared online"],
  depots: ["Bus stations", "Warehouses"],
  despot: ["Tyrant", "Dictator"],
  poster: ["Wall hanging", "Movie ad"],
  presto: ["Magician's word", "Very fast, musically"],
  tropes: ["Clichés", "Figures of speech"],
  praise: ["Compliment", "Acclaim"],
  aspire: ["Aim high", "Hope to be"],
  priest: ["Clergyman", "Father"],
  stripe: ["Zebra line", "Chevron"],
  sprite: ["Fairy", "Pixie"],
  ripest: ["Most mature, as fruit", "Readiest to pick"],
  prince: ["Heir", "Royal son"],
  pincer: ["Crab claw", "___ movement"],
  prints: ["Photos", "Publishes"],
  sprint: ["Dash", "Run fast"],
  remind: ["Jog the memory", "Nudge"],
  minder: ["Babysitter", "Bodyguard"],
  result: ["Outcome", "Score"],
  luster: ["Shine", "Sheen"],
  rustle: ["Leafy sound", "Steal cattle"],
  retain: ["Keep", "Hold on to"],
  retina: ["Eye lining", "Scan for ID"],
  rifles: ["Guns", "Rummages"],
  fliers: ["Leaflets", "Pilots"],
  lifers: ["Long-term inmates", "Career soldiers"],
  rights: ["Bill of ___", "Entitlements"],
  girths: ["Saddle straps", "Waistlines"],
  runway: ["Catwalk", "Airstrip"],
  unwary: ["Careless", "Off guard"],
  sample: ["Taste", "Specimen"],
  maples: ["Syrup trees", "Canadian leaves"],
  scored: ["Tallied", "Won points"],
  decors: ["Interior styles", "Room looks"],
  coders: ["Programmers", "Devs"],
  credos: ["Beliefs", "Mottos"],
  scrape: ["Graze", "Tight spot"],
  capers: ["Heists", "Pickled buds"],
  recaps: ["Summaries", "TV \"previously on\" bits"],
  spacer: ["Gap filler", "Tile gap piece"],
  pacers: ["Race rabbits", "Indiana NBA team"],
  scream: ["Yell", "Munch painting"],
  creams: ["Lotions", "Dairy toppings"],
  search: ["Look for", "Hunt"],
  arches: ["Doorway curves", "Foot parts"],
  chaser: ["Drink after a shot", "Storm ___"],
  senior: ["Twelfth-grader", "Elder"],
  nosier: ["More prying", "Snoopier"],
  serial: ["Podcast format", "Cereal's sound-alike"],
  sailer: ["Ship, by speed", "Vessel"],
  shared: ["Split", "Posted, like a meme"],
  dasher: ["Reindeer", "Churn plunger"],
  shovel: ["Spade", "Dig"],
  hovels: ["Shacks", "Huts"],
  shrine: ["Holy place", "Altar"],
  shiner: ["Black eye", "Bootblack"],
  signal: ["Sign", "Blinker"],
  aligns: ["Lines up", "Straightens"],
  silver: ["Second place", "Argent"],
  livers: ["Organs", "Foie gras source"],
  sliver: ["Splinter", "Thin slice"],
  slower: ["Less fast", "More like a snail"],
  lowers: ["Drops", "Reduces"],
  snatch: ["Grab", "Seize"],
  chants: ["Crowd cheers", "Gregorian songs"],
  solemn: ["Grave", "Serious"],
  lemons: ["Duds, as cars", "Citrus"],
  melons: ["Cantaloupes", "Honeydews"],
  sought: ["Looked for", "Pursued"],
  toughs: ["Thugs", "Hoods"],
  spider: ["Web spinner", "Arachnid"],
  prides: ["Lion groups", "Self-respects"],
  stance: ["Position", "Posture"],
  ascent: ["Climb", "Rise"],
  stared: ["Gawked", "Gazed"],
  trades: ["Swaps", "Jobs"],
  treads: ["Tire grooves", "Steps"],
  starve: ["Go hungry", "Famish"],
  averts: ["Turns away", "Prevents"],
  streak: ["Run", "Stripe"],
  skater: ["Rink athlete", "Boarder"],
  takers: ["Buyers", "Accepters"],
  strike: ["Hit", "Walkout"],
  trikes: ["Tricycles", "Kid's three-wheelers"],
  stroke: ["Swim style", "Caress"],
  stoker: ["Fire feeder", "Dracula's author"],
  subtle: ["Faint", "Understated"],
  bustle: ["Hustle and ___", "Dress padding"],
  bluest: ["Saddest", "Most azure"],
  sublet: ["Rent out", "Sublease"],
  throne: ["Royal seat", "Crown's seat"],
  hornet: ["Stinger", "Wasp"],
  traced: ["Copied", "Tracked"],
  redact: ["Black out", "Censor"],
  traces: ["Tracks", "Hints"],
  crates: ["Boxes", "Moving boxes"],
  caster: ["Furniture wheel", "Spell-___"],
  reacts: ["Responds", "Answers"],
  recast: ["Reshape", "Remake"],
  trance: ["Daze", "Hypnotic state"],
  nectar: ["Bee food", "Sweet liquid"],
  canter: ["Gallop's cousin", "Easy gait"],
  recant: ["Take back", "Retract"],
  trials: ["Tests", "Hardships"],
  trails: ["Paths", "Hikes"],
  tribes: ["Clans", "Groups"],
  biters: ["Nippers", "Mosquitoes"],
  unable: ["Can't", "Incapable"],
  nebula: ["Star cloud", "Gas cloud"],
  voters: ["Electors", "Poll-goers"],
  strove: ["Tried", "Endeavored"],
  troves: ["Hoards", "Treasures"],
  waters: ["Irrigates", "Territorial seas"],
  waster: ["Squanderer", "Wastrel"],
  winter: ["Cold season", "Snow season"],
  twiner: ["Climbing vine", "Clinger"],
  wolves: ["Pack animals", "Predators"],
  vowels: ["A, E, I, O, U", "Wheel of Fortune buys"],
  wonder: ["Marvel", "Awe"],
  downer: ["Buzzkill", "Depressant"],
};

export interface ClueEntry {
  text: string;
  /** A true cryptic (definition + wordplay) rather than a straight clue. */
  cryptic: boolean;
  /** For a cryptic: how the wordplay works. */
  how?: string;
}

/**
 * The clue for `word` on its `n`-th appearance: straight, then a second
 * straight clue, then a cryptic — and round again. A repeat day never
 * shows the last clue again, and one day in three is cryptic.
 */
export function clueFor(word: string, n = 0): ClueEntry {
  const straight = CLUES[word] ?? [];
  const cryptic = CRYPTIC[word];
  const rotation: ClueEntry[] = [
    ...straight.map((text) => ({ text, cryptic: false })),
    ...(cryptic ? [{ text: cryptic.clue, cryptic: true, how: cryptic.how }] : []),
  ];
  if (!rotation.length) return { text: "", cryptic: false };
  return rotation[((n % rotation.length) + rotation.length) % rotation.length];
}
