/**
 * One true cryptic clue per answer word: a definition at one end plus
 * wordplay that builds the answer another way. `how` is the parse — shown
 * on the results card after a cryptic day, and what a reviewer checks.
 *
 * No ANAGRAM cryptics: the letter pad already shows the six letters, so
 * "shuffled" wordplay would hand the answer over. The toolkit is charades
 * (A + B), containers, hidden words, sound-alikes, deletions and — where a
 * word resists — an honest double definition.
 *
 * Conventional abbreviations: ED editor, ER hesitation, RS Royal Society,
 * EL elevated railway, S son, T time, D died, R right, C about, RE on/about,
 * EST establishment, OR gold, CE Church of England, CH church, ST street;
 * DE/LE/LES/UN/ET/FIN/MER are French, ES/SI Spanish, DER German.
 *
 * DRAFTS: AI-written, awaiting the human review pass before launch.
 */
export interface Cryptic {
  clue: string;
  how: string;
}

export const CRYPTIC: Readonly<Record<string, Cryptic>> = {
  angels: { clue: "Heavenly hosts backing startups", how: "Double definition" },
  angles: { clue: "Fishes for viewpoints", how: "Double definition: angles (fishes) / angles (viewpoints)" },
  begins: { clue: "Starts to exist with spirit and son", how: "BE (exist) + GIN (spirit) + S (son)" },
  beings: { clue: "Existence plus son gives creatures", how: "BEING (existence) + S (son)" },
  brakes: { clue: "Stoppers from British garden tools", how: "B (British) + RAKES" },
  breaks: { clue: "Snaps, or holiday recesses", how: "Double definition" },
  burden: { clue: "Load: prickly seed head in a lair", how: "BUR + DEN" },
  burned: { clue: "Scorched a stream for the editor", how: "BURN (Scottish stream) + ED (editor)" },
  caring: { clue: "Kind vehicle with a headless ring", how: "CAR + (r)ING" },
  racing: { clue: "Sport of kings, pounding", how: "Double definition" },
  course: { clue: "Dish about ours, then east", how: "C (about) + OURS + E (east)" },
  source: { clue: "Origin: bitter Church of England", how: "SOUR + CE (Church of England)" },
  credit: { clue: "Recognition: street rep and sex appeal", how: "CRED (street cred) + IT (sex appeal)" },
  direct: { clue: "Straight, dreadful, then Connecticut", how: "DIRE + CT (Connecticut)" },
  danger: { clue: "Peril is daughter's rage", how: "D (daughter) + ANGER" },
  garden: { clue: "Fish in a lair, where roses grow", how: "GAR (fish) + DEN (lair)" },
  denial: { clue: "Refusal: study, one, and Al", how: "DEN (study) + I (one) + AL" },
  nailed: { clue: "Aced: fingertip part for editor", how: "NAIL + ED (editor)" },
  depart: { clue: "Leave \"of,\" in Paris, a role", how: "DE (French \"of\") + PART (role)" },
  parted: { clue: "Split average with Ted", how: "PAR (average) + TED" },
  design: { clue: "Plan of, in Paris, an omen", how: "DE (French \"of\") + SIGN (omen)" },
  signed: { clue: "Autographed notice for the editor", how: "SIGN (notice) + ED (editor)" },
  duties: { clue: "Tasks: \"of the,\" in Paris, ties", how: "DU (French \"of the\") + TIES" },
  suited: { clue: "Matched case for the editor", how: "SUIT (case) + ED (editor)" },
  equals: { clue: "Peers even with son", how: "EQUAL (even) + S (son)" },
  squeal: { clue: "Rat, or a pig's cry", how: "Double definition" },
  escort: { clue: "Usher, key and scrap", how: "ESC (escape key) + ORT (scrap)" },
  sector: { clue: "Zone: cult with gold", how: "SECT (cult) + OR (gold)" },
  forest: { clue: "Woods in favor of establishment", how: "FOR (in favor of) + EST (establishment)" },
  foster: { clue: "Nurture a child who isn't yours", how: "Double definition (bring up / encourage)" },
  groans: { clue: "Moans: good horses", how: "G (good) + ROANS (horses)" },
  organs: { clue: "Kidneys, say: instrument and son", how: "ORGAN + S (son)" },
  hatred: { clue: "Loathing: cap, communist", how: "HAT + RED (communist)" },
  thread: { clue: "Strand: \"the,\" cut short, then study", how: "TH(e) + READ (study)" },
  hostel: { clue: "Cheap lodging: compere with railway", how: "HOST (compere) + EL (elevated railway)" },
  hotels: { clue: "Inns: spicy elevated trains", how: "HOT (spicy) + ELS (elevated railways)" },
  ideals: { clue: "Standards: one's bargains", how: "I (one) + DEALS" },
  ladies: { clue: "Women: L.A. expires", how: "LA + DIES" },
  sailed: { clue: "Went by boat: canvas for editor", how: "SAIL (canvas) + ED (editor)" },
  ignore: { clue: "Snub in big no-reply, partly", how: "Hidden: bIG NO REply" },
  region: { clue: "Area: king's charged particle", how: "REG (king) + ION" },
  insect: { clue: "Bug at home with a cult", how: "IN (at home) + SECT (cult)" },
  nicest: { clue: "Kindest French city, street", how: "NICE + ST (street)" },
  learnt: { clue: "Picked up: study with time", how: "LEARN + T (time)" },
  rental: { clue: "Leased flat: tear with Al", how: "RENT (tear) + AL" },
  lights: { clue: "Lamps: not heavy, son", how: "LIGHT (not heavy) + S (son)" },
  slight: { clue: "Snub: small lamp", how: "S (small) + LIGHT (lamp)" },
  listen: { clue: "Hear: register, then printer's space", how: "LIST (register) + EN (printer's space)" },
  silent: { clue: "Mum: yes in Spain, loaned", how: "SI (Spanish \"yes\") + LENT (loaned)" },
  lowest: { clue: "Bottom: moo with establishment", how: "LOW (moo) + EST (establishment)" },
  towels: { clue: "Dryers pull elevated trains", how: "TOW (pull) + ELS (elevated railways)" },
  marine: { clue: "Of the sea, or a soldier", how: "Double definition" },
  remain: { clue: "Stay on the sea", how: "RE (on) + MAIN (the sea)" },
  master: { clue: "Expert: pole, then hesitation", how: "MAST (pole) + ER (hesitation)" },
  stream: { clue: "Brook: street with paper", how: "ST (street) + REAM (paper)" },
  models: { clue: "Poses: fashion, left, son", how: "MODE (fashion) + L (left) + S (son)" },
  seldom: { clue: "Rarely market, briefly, with a master", how: "SEL(l) (market, briefly) + DOM (master)" },
  nights: { clue: "Evenings: chessmen losing king", how: "(k)NIGHTS, minus K (king)" },
  things: { clue: "Objects: whatsit and son", how: "THING (whatsit) + S (son)" },
  patrol: { clue: "Beat: tap, then roll cut short", how: "PAT (tap) + ROL(l)" },
  portal: { clue: "Gateway: harbor with Al", how: "PORT (harbor) + AL" },
  pilots: { clue: "Flyers: pious, plenty", how: "PI (pious) + LOTS (plenty)" },
  pistol: { clue: "Gun in tulip is tolerant", how: "Hidden: tuliP IS TOLerant" },
  plains: { clue: "Prairies: simple son", how: "PLAIN (simple) + S (son)" },
  spinal: { clue: "Of the backbone: turn with Al", how: "SPIN (turn) + AL" },
  ransom: { clue: "Hostage price ran some way", how: "Hidden: RAN SOMe" },
  romans: { clue: "Caesar's people: novel with son", how: "ROMAN (French \"novel\") + S (son)" },
  resign: { clue: "Quit about a notice", how: "RE (about) + SIGN (notice)" },
  singer: { clue: "Vocalist: croon, hesitation", how: "SING (croon) + ER (hesitation)" },
  sacred: { clue: "Holy pouch in the red", how: "SAC (pouch) + RED" },
  scared: { clue: "Frightened: son minded", how: "S (son) + CARED (minded)" },
  spared: { clue: "Let off: resort, communist", how: "SPA (resort) + RED (communist)" },
  spread: { clue: "Toast topping: starting price, read", how: "SP (starting price) + READ" },
  stable: { clue: "Steady small piece of furniture", how: "S (small) + TABLE (furniture)" },
  tables: { clue: "Charts: bill with \"the,\" in Paris", how: "TAB (bill) + LES (French \"the\")" },
  stayed: { clue: "Remained: corset for editor", how: "STAY (corset) + ED (editor)" },
  steady: { clue: "Firm place, unknown", how: "STEAD (place) + Y (unknown)" },
  strain: { clue: "Son's railway line? Pull a muscle", how: "S (son) + TRAIN" },
  trains: { clue: "Coaches: time and showers", how: "T (time) + RAINS (showers)" },
  struck: { clue: "Hit small rig", how: "S (small) + TRUCK (rig)" },
  trucks: { clue: "Rigs: time for scrums", how: "T (time) + RUCKS (scrums)" },
  wander: { clue: "Roam: magic stick, hesitation", how: "WAND + ER (hesitation)" },
  warden: { clue: "Keeper of conflict den", how: "WAR (conflict) + DEN" },
  warned: { clue: "Cautioned: battle for Ned", how: "WAR (battle) + NED" },
  actors: { clue: "Players: law with golds", how: "ACT (law) + ORS (golds)" },
  costar: { clue: "Fellow lead: company celebrity", how: "CO (company) + STAR (celebrity)" },
  castor: { clue: "Oil: throw gold", how: "CAST (throw) + OR (gold)" },
  aliens: { clue: "Outsiders: a claims on property", how: "A + LIENS (claims on property)" },
  saline: { clue: "Salty: South Africa's line", how: "SA (South Africa) + LINE" },
  ashore: { clue: "On land: a coast", how: "A + SHORE (coast)" },
  hoarse: { clue: "Croaky mount, we hear", how: "Sounds like HORSE (mount)" },
  badger: { clue: "Pester: evil German", how: "BAD (evil) + GER (German)" },
  barged: { clue: "Pushed in: boat, then died", how: "BARGE (boat) + D (died)" },
  barely: { clue: "Hardly: pub by Ely", how: "BAR (pub) + ELY (English city)" },
  barley: { clue: "Grain: pub, meadow", how: "BAR (pub) + LEY (meadow)" },
  bleary: { clue: "Dim-eyed: British meadow, railway", how: "B (British) + LEA (meadow) + RY (railway)" },
  blamed: { clue: "Faulted: fault, died", how: "BLAME (fault) + D (died)" },
  bedlam: { clue: "Chaos in bed with a lamb, cut short", how: "BED + LAM(b)" },
  boiler: { clue: "Heater: seethe, hesitation", how: "BOIL (seethe) + ER (hesitation)" },
  reboil: { clue: "Heat again about a pimple", how: "RE (about) + BOIL (pimple)" },
  breast: { clue: "Chest in timbre astounds", how: "Hidden: timBRE ASTounds" },
  barest: { clue: "Most minimal pub establishment", how: "BAR (pub) + EST (establishment)" },
  breath: { clue: "Air: British garland, beheaded", how: "B (British) + (w)REATH (garland)" },
  bather: { clue: "Swimmer: tub, hesitation", how: "BATH (tub) + ER (hesitation)" },
  bridal: { clue: "Of a wedding, horse's headgear, we hear", how: "Sounds like BRIDLE" },
  ribald: { clue: "Racy: Rhode Island, hairless", how: "RI (Rhode Island) + BALD (hairless)" },
  bruise: { clue: "Mark: British trick, one inside", how: "B (British) + RU(I)SE (trick holding one)" },
  buries: { clue: "Inters fruits, we hear", how: "Sounds like BERRIES" },
  busier: { clue: "More hectic coach at pier, headless", how: "BUS (coach) + (p)IER" },
  rubies: { clue: "Gems in cherub I estimate", how: "Hidden: cheRUB I EStimate" },
  busted: { clue: "Caught: statue for the editor", how: "BUST (statue) + ED (editor)" },
  debuts: { clue: "Premieres: \"of,\" in Paris, objections", how: "DE (French \"of\") + BUTS (objections)" },
  buster: { clue: "Pal: statue, hesitation", how: "BUST (statue) + ER (hesitation)" },
  brutes: { clue: "Thugs: dry wine is, in Madrid", how: "BRUT (dry wine) + ES (Spanish \"is\")" },
  tubers: { clue: "Potatoes: subway, Royal Society", how: "TUBE (subway) + RS (Royal Society)" },
  rebuts: { clue: "Counters about objections", how: "RE (about) + BUTS (objections)" },
  candle: { clue: "Light: tin, daughter, \"the\" in Paris", how: "CAN (tin) + D (daughter) + LE (French \"the\")" },
  lanced: { clue: "Pierced: spear, died", how: "LANCE (spear) + D (died)" },
  cartel: { clue: "Ring: wagon on elevated railway", how: "CART (wagon) + EL (elevated railway)" },
  claret: { clue: "Wine: Irish county, time", how: "CLARE (Irish county) + T (time)" },
  castle: { clue: "Rook: throw \"the,\" in Paris", how: "CAST (throw) + LE (French \"the\")" },
  cleats: { clue: "Shoes found in uncle at sea", how: "Hidden: unCLE AT Sea" },
  chains: { clue: "Links: tea with ins", how: "CHA (tea) + INS" },
  chinas: { clue: "Porcelains: jaw as", how: "CHIN (jaw) + AS" },
  charts: { clue: "Graphs: about deer", how: "C (about) + HARTS (deer)" },
  starch: { clue: "Stiffener: celebrity church", how: "STAR (celebrity) + CH (church)" },
  cinema: { clue: "Films: movie camera, mother", how: "CINE (movie camera) + MA (mother)" },
  anemic: { clue: "Weak: a northeast microphone", how: "A + NE (northeast) + MIC (microphone)" },
  iceman: { clue: "Cool one: diamonds, fellow", how: "ICE (diamonds) + MAN (fellow)" },
  clears: { clue: "Acquits about kings", how: "C (about) + LEARS (kings)" },
  scaler: { clue: "Climber: flake, right", how: "SCALE (flake) + R (right)" },
  cursed: { clue: "Swore: oath, died", how: "CURSE (oath) + D (died)" },
  crudes: { clue: "Oils: muck is, in Madrid", how: "CRUD (muck) + ES (Spanish \"is\")" },
  dancer: { clue: "Hoofer: ball, right", how: "DANCE (ball) + R (right)" },
  craned: { clue: "Stretched: bird, died", how: "CRANE (bird) + D (died)" },
  dances: { clue: "Proms: ball and son", how: "DANCE (ball) + S (son)" },
  ascend: { clue: "Climb: a dispatch holding \"about\"", how: "A + S(C)END (send holding C, about)" },
  deacon: { clue: "Church officer: drug agency, trick", how: "DEA (drug agency) + CON (trick)" },
  canoed: { clue: "Paddled: boat, died", how: "CANOE (boat) + D (died)" },
  debris: { clue: "Rubble: debutante, Rhode Island, son", how: "DEB + RI (Rhode Island) + S (son)" },
  brides: { clue: "Veil wearers: British trips", how: "B (British) + RIDES (trips)" },
  detail: { clue: "Fine point: \"of,\" in Paris, end", how: "DE (French \"of\") + TAIL (end)" },
  dilate: { clue: "Widen: Diana, dead", how: "DI (Diana) + LATE (dead)" },
  tailed: { clue: "Followed: end for the editor", how: "TAIL (end) + ED (editor)" },
  detour: { clue: "Roundabout way \"of\" trip, in Paris", how: "DE (French \"of\") + TOUR (trip)" },
  routed: { clue: "Crushed: defeat for the editor", how: "ROUT (defeat) + ED (editor)" },
  toured: { clue: "Went on the road: trip, editor", how: "TOUR (trip) + ED (editor)" },
  diaper: { clue: "Baby wear: Diana's mimic", how: "DI (Diana) + APER (mimic)" },
  paired: { clue: "Matched: couple, editor", how: "PAIR (couple) + ED (editor)" },
  repaid: { clue: "Settled about salaried", how: "RE (about) + PAID (salaried)" },
  donate: { clue: "Give: put on, dined", how: "DON (put on) + ATE (dined)" },
  atoned: { clue: "Made amends: a fit", how: "A + TONED (fit)" },
  drives: { clue: "Motivations: doctor and composer", how: "DR (doctor) + IVES (Charles Ives)" },
  divers: { clue: "Scuba fans: plunge, Royal Society", how: "DIVE (plunge) + RS (Royal Society)" },
  drones: { clue: "Male bees: doctor's singles", how: "DR (doctor) + ONES (singles)" },
  snored: { clue: "Slept noisily: rattle, died", how: "SNORE + D (died)" },
  editor: { clue: "Red-pen wielder: revise gold", how: "EDIT (revise) + OR (gold)" },
  rioted: { clue: "Ran amok: a scream, then Ed", how: "RIOT (a scream) + ED" },
  triode: { clue: "Tube: three, poem", how: "TRI (three) + ODE (poem)" },
  failed: { clue: "Flunked: miss, editor", how: "FAIL (miss) + ED (editor)" },
  afield: { clue: "Far away: a meadow", how: "A + FIELD (meadow)" },
  faster: { clue: "Quicker abstainer", how: "Double definition: quicker / one who fasts" },
  strafe: { clue: "Rake with fire, or sidestep shooting", how: "Double definition" },
  filter: { clue: "Strainer, or a photo effect", how: "Double definition" },
  lifter: { clue: "Weight trainer: elevator, hesitation", how: "LIFT (elevator) + ER (hesitation)" },
  trifle: { clue: "Small matter: time for a gun", how: "T (time) + RIFLE (gun)" },
  finest: { clue: "Best: \"end,\" in Paris, establishment", how: "FIN (French \"end\") + EST (establishment)" },
  infest: { clue: "Overrun: at home with a festival", how: "IN (at home) + FEST (festival)" },
  finger: { clue: "Digit: \"end,\" in Paris, German", how: "FIN (French \"end\") + GER (German)" },
  fringe: { clue: "Edge: loud call, energy", how: "F (loud) + RING (call) + E (energy)" },
  forces: { clue: "Services: power, son", how: "FORCE (power) + S (son)" },
  fresco: { clue: "Mural: new, not hot, company", how: "FRES(h) (new, minus H for hot) + CO (company)" },
  formed: { clue: "Shaped: class, editor", how: "FORM (class) + ED (editor)" },
  deform: { clue: "Warp \"of\" shape, in Paris", how: "DE (French \"of\") + FORM (shape)" },
  freaks: { clue: "Oddballs: whim, son", how: "FREAK (whim) + S (son)" },
  fakers: { clue: "Phonies: sham, Royal Society", how: "FAKE (sham) + RS (Royal Society)" },
  friend: { clue: "Pal: Friday's finish", how: "FRI (Friday) + END (finish)" },
  finder: { clue: "Locator: \"end\" of the German", how: "FIN (French \"end\") + DER (German \"the\")" },
  gifted: { clue: "Talented: present, editor", how: "GIFT (present) + ED (editor)" },
  fidget: { clue: "Squirm: spike, obtain", how: "FID (sailor's spike) + GET (obtain)" },
  golden: { clue: "Gilded in big olden days", how: "Hidden: biG OLDEN days" },
  longed: { clue: "Pined: tall, editor", how: "LONG (tall) + ED (editor)" },
  grapes: { clue: "Vine fruit: Greek monkeys", how: "GR (Greek) + APES (monkeys)" },
  pagers: { clue: "Beepers: sheet, Royal Society", how: "PAGE (sheet) + RS (Royal Society)" },
  grunts: { clue: "Foot soldiers: good weaklings", how: "G (good) + RUNTS (weaklings)" },
  strung: { clue: "Threaded: street step", how: "ST (street) + RUNG (step)" },
  hearts: { clue: "Suit: he, crafts", how: "HE + ARTS (crafts)" },
  earths: { clue: "Soils: fireplaces losing hot", how: "(h)EARTHS, minus H (hot)" },
  haters: { clue: "Critics: cap, hesitations", how: "HAT (cap) + ERS (hesitations)" },
  hustle: { clue: "Hurry, or a con", how: "Double definition" },
  sleuth: { clue: "Private eye, or to track", how: "Double definition" },
  images: { clue: "Pictures: one with wizards", how: "I (one) + MAGES (wizards)" },
  ageism: { clue: "Bias: era, doctrine", how: "AGE (era) + ISM (doctrine)" },
  inches: { clue: "Creeps home with chests cut short", how: "IN (home) + CHES(t)" },
  niches: { clue: "Nooks found in Munich estates", how: "Hidden: muNICH ESTates" },
  insult: { clue: "Offend at home, sultan cut", how: "IN (at home) + SULT(an)" },
  sunlit: { clue: "Bright: star, burning", how: "SUN (star) + LIT (burning)" },
  itself: { clue: "By ___: sex appeal, ego", how: "IT (sex appeal) + SELF (ego)" },
  stifle: { clue: "Smother, at last if left", how: "Hidden: laST IF LEft" },
  filets: { clue: "Cuts: loud one allows", how: "F (loud) + I (one) + LETS (allows)" },
  lasted: { clue: "Endured: final editor", how: "LAST (final) + ED (editor)" },
  deltas: { clue: "Mouths: Greek letter and son", how: "DELTA + S (son)" },
  layers: { clue: "Tiers: song, hesitations", how: "LAY (song) + ERS (hesitations)" },
  relays: { clue: "Passes on about songs", how: "RE (about) + LAYS (songs)" },
  slayer: { clue: "Killer: son, hen", how: "S (son) + LAYER (hen)" },
  layout: { clue: "Design: song, away", how: "LAY (song) + OUT (away)" },
  outlay: { clue: "Expense: away song", how: "OUT (away) + LAY (song)" },
  linked: { clue: "Joined: chain part, editor", how: "LINK (chain part) + ED (editor)" },
  kindle: { clue: "Ignite nice \"the,\" in Paris", how: "KIND (nice) + LE (French \"the\")" },
  listed: { clue: "Itemized: register for editor", how: "LIST (register) + ED (editor)" },
  delist: { clue: "Remove \"of\" catalog, in Paris", how: "DE (French \"of\") + LIST (catalog)" },
  locker: { clue: "Storage: bolt, hesitation", how: "LOCK (bolt) + ER (hesitation)" },
  relock: { clue: "Bolt again about a tress", how: "RE (about) + LOCK (tress)" },
  lovers: { clue: "Sweethearts: zero, Royal Society", how: "LOVE (zero) + RS (Royal Society)" },
  solver: { clue: "Puzzler: crack, right", how: "SOLVE (crack) + R (right)" },
  maiden: { clue: "First servant, then space", how: "MAID (servant) + EN (printer's space)" },
  median: { clue: "Middle: press, new", how: "MEDIA (press) + N (new)" },
  marble: { clue: "Stone: spoil, capable minus A", how: "MAR (spoil) + (a)BLE" },
  ramble: { clue: "Wander: right stroll", how: "R (right) + AMBLE (stroll)" },
  medals: { clue: "Honors: sea with Als", how: "MED (Mediterranean) + ALS" },
  damsel: { clue: "Maiden: mothers, railway", how: "DAMS (mothers) + EL (elevated railway)" },
  mental: { clue: "Of the mind: guys, tall, cut short", how: "MEN (guys) + TAL(l)" },
  lament: { clue: "Mourn: weak New Testament", how: "LAME (weak) + NT (New Testament)" },
  mantle: { clue: "Cloak, or the earth's layer", how: "Double definition" },
  minute: { clue: "Tiny minimum pickup", how: "MIN (minimum) + UTE (pickup truck)" },
  minuet: { clue: "Dance: male in you, and in Paris", how: "M (male) + IN + U (you) + ET (French \"and\")" },
  mister: { clue: "Mr.: fog, hesitation", how: "MIST (fog) + ER (hesitation)" },
  merits: { clue: "Virtues: sea in Paris, its", how: "MER (French \"sea\") + ITS" },
  timers: { clue: "Clocks: Tim, hesitations", how: "TIM + ERS (hesitations)" },
  remits: { clue: "Sends: sleep phase, its", how: "REM (sleep phase) + ITS" },
  morals: { clue: "Ethics: more, briefly, with Als", how: "MOR(e) + ALS" },
  molars: { clue: "Grinders: moment, Lars", how: "MO (moment) + LARS" },
  neural: { clue: "Of nerves: northeast mountains", how: "NE (northeast) + URAL (mountains)" },
  unreal: { clue: "Fake: \"a\" in Paris, genuine", how: "UN (French \"a\") + REAL (genuine)" },
  novels: { clue: "Books: new, son", how: "NOVEL (new) + S (son)" },
  sloven: { clue: "Slob: son, darling, new", how: "S (son) + LOVE (darling) + N (new)" },
  oceans: { clue: "Seas: ring, church, answers", how: "O (ring) + CE (church) + ANS (answers)" },
  canoes: { clue: "Boats: about refusals", how: "CA (about) + NOES (refusals)" },
  ordeal: { clue: "Trial: gold bargain", how: "OR (gold) + DEAL (bargain)" },
  loader: { clue: "Forklift: burden, hesitation", how: "LOAD (burden) + ER (hesitation)" },
  reload: { clue: "Refresh about a burden", how: "RE (about) + LOAD (burden)" },
  others: { clue: "The rest of the siblings, first two gone", how: "(br)OTHERS" },
  throes: { clue: "Spasms: pitches, we hear", how: "Sounds like THROWS (pitches)" },
  owners: { clue: "Holders: admit hesitations", how: "OWN (admit) + ERS (hesitations)" },
  worsen: { clue: "Deteriorate: poorer, new", how: "WORSE (poorer) + N (new)" },
  parcel: { clue: "Package: standard, film frame", how: "PAR (standard) + CEL (film frame)" },
  placer: { clue: "Gold deposit: spot, right", how: "PLACE (spot) + R (right)" },
  parent: { clue: "Mom: average, ear-nose-throat", how: "PAR (average) + ENT (ear, nose and throat)" },
  entrap: { clue: "Snare: printer's space, mouth", how: "EN (printer's space) + TRAP (mouth)" },
  partly: { clue: "Somewhat role, then lastly's end", how: "PART (role) + (last)LY" },
  paltry: { clue: "Meager: friend's attempt", how: "PAL (friend) + TRY (attempt)" },
  patron: { clue: "Sponsor: tap Ron", how: "PAT (tap) + RON" },
  tarpon: { clue: "Fish: tarpaulin on", how: "TARP (tarpaulin) + ON" },
  planes: { clue: "Aircraft: level, son", how: "PLANE (level) + S (son)" },
  panels: { clue: "Groups: criticize trains", how: "PAN (criticize) + ELS (elevated railways)" },
  planet: { clue: "World: scheme and, in Paris", how: "PLAN (scheme) + ET (French \"and\")" },
  platen: { clue: "Roller: dish, new", how: "PLATE (dish) + N (new)" },
  plates: { clue: "Dishes: parking, deceased", how: "P (parking) + LATES (deceased)" },
  staple: { clue: "Fastener in past aplenty", how: "Hidden: paST APLEnty" },
  petals: { clue: "Flower parts: dear Als", how: "PET (dear) + ALS" },
  pastel: { clue: "Soft color: gone railway", how: "PAST (gone) + EL (elevated railway)" },
  pleats: { clue: "Folds: appeal, time, son", how: "PLEA (appeal) + T (time) + S (son)" },
  palest: { clue: "Most wan: friend's establishment", how: "PAL (friend) + EST (establishment)" },
  player: { clue: "Gamer: drama, hesitation", how: "PLAY (drama) + ER (hesitation)" },
  replay: { clue: "Rerun about a drama", how: "RE (about) + PLAY (drama)" },
  pearly: { clue: "Lustrous: gem, unknown", how: "PEARL (gem) + Y (unknown)" },
  posted: { clue: "Mailed: stake, editor", how: "POST (stake) + ED (editor)" },
  depots: { clue: "Warehouses \"of\" pans, in Paris", how: "DE (French \"of\") + POTS (pans)" },
  despot: { clue: "Tyrant: \"of the\" in Paris, pot", how: "DES (French \"of the\") + POT" },
  poster: { clue: "Wall hanging: mail, hesitation", how: "POST (mail) + ER (hesitation)" },
  presto: { clue: "Magic word: PR, establishment, ring", how: "PR (public relations) + EST (establishment) + O (ring)" },
  tropes: { clue: "Clichés: time lines", how: "T (time) + ROPES (lines)" },
  praise: { clue: "Laud quiet lift", how: "P (quiet) + RAISE (lift)" },
  aspire: { clue: "Aim high, a steeple", how: "A + SPIRE (steeple)" },
  priest: { clue: "Father: snoops, time", how: "PRIES (snoops) + T (time)" },
  stripe: { clue: "Line: undress, energy", how: "STRIP (undress) + E (energy)" },
  sprite: { clue: "Fairy: spar, energy", how: "SPRIT (spar) + E (energy)" },
  ripest: { clue: "Most mature: tear, establishment", how: "RIP (tear) + EST (establishment)" },
  prince: { clue: "Heir: publish, briefly, church", how: "PRIN(t) + CE (church)" },
  pincer: { clue: "Claw found in spin certainly", how: "Hidden: sPIN CERtainly" },
  prints: { clue: "Photos: publish, son", how: "PRINT (publish) + S (son)" },
  sprint: { clue: "Dash: son publishes", how: "S (son) + PRINT (publishes)" },
  remind: { clue: "Prompt on care", how: "RE (on) + MIND (care)" },
  minder: { clue: "Bodyguard: care, hesitation", how: "MIND (care) + ER (hesitation)" },
  result: { clue: "Outcome about sultan cut", how: "RE (about) + SULT(an)" },
  luster: { clue: "Shine: desire, hesitation", how: "LUST (desire) + ER (hesitation)" },
  rustle: { clue: "Steal cattle: corrosion, \"the\" in Paris", how: "RUST (corrosion) + LE (French \"the\")" },
  retain: { clue: "Keep: on time, a, at home", how: "RE (on) + T (time) + A + IN (at home)" },
  retina: { clue: "Eye part: about metal, a", how: "RE (about) + TIN (metal) + A" },
  rifles: { clue: "Guns, or rummages", how: "Double definition" },
  fliers: { clue: "Pilots: loud fibbers", how: "F (loud) + LIERS (fibbers)" },
  lifers: { clue: "Long-termers: existence, Royal Society", how: "LIFE (existence) + RS (Royal Society)" },
  rights: { clue: "Entitlements: correct, son", how: "RIGHT (correct) + S (son)" },
  girths: { clue: "Waistlines, or saddle straps", how: "Double definition" },
  runway: { clue: "Catwalk: dash, path", how: "RUN (dash) + WAY (path)" },
  unwary: { clue: "Off guard: \"a\" in Paris, cautious", how: "UN (French \"a\") + WARY (cautious)" },
  sample: { clue: "Taste: son, plenty", how: "S (son) + AMPLE (plenty)" },
  maples: { clue: "Syrup trees: chart \"the\" in Paris", how: "MAP (chart) + LES (French \"the\")" },
  scored: { clue: "Tallied: son, hollowed", how: "S (son) + CORED (hollowed)" },
  decors: { clue: "Styles: December golds", how: "DEC (December) + ORS (golds)" },
  coders: { clue: "Devs: cipher, Royal Society", how: "CODE (cipher) + RS (Royal Society)" },
  credos: { clue: "Beliefs: street rep, bones", how: "CRED (street cred) + OS (bones)" },
  scrape: { clue: "Graze: fight, energy", how: "SCRAP (fight) + E (energy)" },
  capers: { clue: "Antics: cloak, Royal Society", how: "CAPE (cloak) + RS (Royal Society)" },
  recaps: { clue: "Summaries about hats", how: "RE (about) + CAPS (hats)" },
  spacer: { clue: "Gap filler: room, right", how: "SPACE (room) + R (right)" },
  pacers: { clue: "Runners: speed, Royal Society", how: "PACE (speed) + RS (Royal Society)" },
  scream: { clue: "Yell: son, the best", how: "S (son) + CREAM (the best)" },
  creams: { clue: "Lotions: about paper stacks", how: "C (about) + REAMS (paper stacks)" },
  search: { clue: "Hunt: scorch church", how: "SEAR (scorch) + CH (church)" },
  arches: { clue: "Curves: arc, males", how: "ARC + HES (males)" },
  chaser: { clue: "Pursuer: hunt, right", how: "CHASE (hunt) + R (right)" },
  senior: { clue: "Elder: senator, one, gold", how: "SEN (senator) + I (one) + OR (gold)" },
  nosier: { clue: "More prying: new willow", how: "N (new) + OSIER (willow)" },
  serial: { clue: "Episodic breakfast food, aloud", how: "Sounds like CEREAL" },
  sailer: { clue: "Ship: canvas, hesitation", how: "SAIL (canvas) + ER (hesitation)" },
  shared: { clue: "Split: portion, died", how: "SHARE (portion) + D (died)" },
  dasher: { clue: "Reindeer: rush, hesitation", how: "DASH (rush) + ER (hesitation)" },
  shovel: { clue: "Spade: son's shack", how: "S (son) + HOVEL (shack)" },
  hovels: { clue: "Shacks: hot books, first missing", how: "H (hot) + (n)OVELS" },
  shrine: { clue: "Holy place: hush, Rhine without H", how: "SH (hush) + R(h)INE" },
  shiner: { clue: "Black eye: gleam, right", how: "SHINE (gleam) + R (right)" },
  signal: { clue: "Blinker: notice with Al", how: "SIGN (notice) + AL" },
  aligns: { clue: "Lines up: a, left, signs beheaded", how: "A + L (left) + (s)IGNS" },
  silver: { clue: "Second place in basil vermouth", how: "Hidden: baSIL VERmouth" },
  livers: { clue: "Organs: exist, Royal Society", how: "LIVE (exist) + RS (Royal Society)" },
  sliver: { clue: "Splinter: son's organ", how: "S (son) + LIVER (organ)" },
  slower: { clue: "Less fast: son drops", how: "S (son) + LOWER (drops)" },
  lowers: { clue: "Drops: moo, hesitations", how: "LOW (moo) + ERS (hesitations)" },
  snatch: { clue: "Grab: son, naturally", how: "S (son) + NATCH (naturally, slang)" },
  chants: { clue: "Crowd cries: about Hampshire", how: "C (about) + HANTS (Hampshire)" },
  solemn: { clue: "Grave: fish, Minnesota", how: "SOLE (fish) + MN (Minnesota)" },
  lemons: { clue: "Duds: \"the\" mountain, in Paris", how: "LE (French \"the\") + MONS (mountain)" },
  melons: { clue: "Round fruits, or heads, slangily", how: "Double definition" },
  sought: { clue: "Looked for: son should", how: "S (son) + OUGHT (should)" },
  toughs: { clue: "Thugs: toward sounds of disgust", how: "TO (toward) + UGHS" },
  spider: { clue: "Web weaver, or a solitaire game", how: "Double definition" },
  prides: { clue: "Lion groups: quiet trips", how: "P (quiet) + RIDES (trips)" },
  stance: { clue: "Posture: Stan, church", how: "STAN + CE (Church of England)" },
  ascent: { clue: "Climb: a smell", how: "A + SCENT (smell)" },
  stared: { clue: "Gawked: celebrity editor", how: "STAR (celebrity) + ED (editor)" },
  trades: { clue: "Jobs: business and son", how: "TRADE (business) + S (son)" },
  treads: { clue: "Steps: time studies", how: "T (time) + READS (studies)" },
  starve: { clue: "Go hungry: celebrity, very, energy", how: "STAR (celebrity) + V (very) + E (energy)" },
  averts: { clue: "Wards off: declare, time, son", how: "AVER (declare) + T (time) + S (son)" },
  streak: { clue: "Stripe: sirloin around \"about\"", how: "ST(RE)AK (steak around RE, about)" },
  skater: { clue: "Rink athlete: fish, right", how: "SKATE (fish) + R (right)" },
  takers: { clue: "Buyers: grab, Royal Society", how: "TAKE (grab) + RS (Royal Society)" },
  strike: { clue: "Hit son's three-wheeler", how: "S (son) + TRIKE (three-wheeler)" },
  trikes: { clue: "Three-wheelers hits, first off", how: "(s)TRIKES" },
  stroke: { clue: "Caress, or a swimming style", how: "Double definition" },
  stoker: { clue: "Fire feeder: fuel, right", how: "STOKE (fuel) + R (right)" },
  subtle: { clue: "Faint: sub, title losing \"it\"", how: "SUB + T(it)LE" },
  bustle: { clue: "Busy activity: statue, \"the\" in Paris", how: "BUST (statue) + LE (French \"the\")" },
  bluest: { clue: "Saddest: music, time", how: "BLUES (music) + T (time)" },
  sublet: { clue: "Rent out: sandwich, allow", how: "SUB (sandwich) + LET (allow)" },
  throne: { clue: "Seat: through, briefly, northeast", how: "THRO (through, briefly) + NE (northeast)" },
  hornet: { clue: "Wasp: trumpet and, in Paris", how: "HORN (trumpet) + ET (French \"and\")" },
  traced: { clue: "Copied: hint, died", how: "TRACE (hint) + D (died)" },
  redact: { clue: "Censor: communist law", how: "RED (communist) + ACT (law)" },
  traces: { clue: "Hints: time, heats", how: "T (time) + RACES (heats)" },
  crates: { clue: "Boxes: about prices", how: "C (about) + RATES (prices)" },
  caster: { clue: "Furniture wheel: throw, hesitation", how: "CAST (throw) + ER (hesitation)" },
  reacts: { clue: "Responds about deeds", how: "RE (about) + ACTS (deeds)" },
  recast: { clue: "Remake about a mold", how: "RE (about) + CAST (mold)" },
  trance: { clue: "Daze: across, briefly, church", how: "TRAN(s) (across, briefly) + CE (church)" },
  nectar: { clue: "Bee food: northeast, about, sailor", how: "NE (northeast) + C (about) + TAR (sailor)" },
  canter: { clue: "Easy gait: jargon, hesitation", how: "CANT (jargon) + ER (hesitation)" },
  recant: { clue: "Retract about jargon", how: "RE (about) + CANT (jargon)" },
  trials: { clue: "Tests: time, Iranian coins", how: "T (time) + RIALS (Iranian coins)" },
  trails: { clue: "Paths: time, bars", how: "T (time) + RAILS (bars)" },
  tribes: { clue: "Clans: time, rib, is in Madrid", how: "T (time) + RIB + ES (Spanish \"is\")" },
  biters: { clue: "Nippers: snack, Royal Society", how: "BITE (snack) + RS (Royal Society)" },
  unable: { clue: "Can't: \"a\" in Paris, capable", how: "UN (French \"a\") + ABLE (capable)" },
  nebula: { clue: "Star cloud: beak, you, L.A.", how: "NEB (beak) + U (you) + LA" },
  voters: { clue: "Electors: ballot, Royal Society", how: "VOTE (ballot) + RS (Royal Society)" },
  strove: { clue: "Tried son's treasure", how: "S (son) + TROVE (treasure)" },
  troves: { clue: "Hoards: time wanders", how: "T (time) + ROVES (wanders)" },
  waters: { clue: "Seas: west ate, Royal Society", how: "W (west) + ATE + RS (Royal Society)" },
  waster: { clue: "Good-for-nothing: west flower", how: "W (west) + ASTER (flower)" },
  winter: { clue: "Cold season: west, bury", how: "W (west) + INTER (bury)" },
  twiner: { clue: "Climbing vine: double, hesitation", how: "TWIN (double) + ER (hesitation)" },
  wolves: { clue: "Pack animals: west cracks, first off", how: "W (west) + (s)OLVES (cracks)" },
  vowels: { clue: "A, E, I: pledge trains", how: "VOW (pledge) + ELS (elevated railways)" },
  wonder: { clue: "Marvel: triumphed, \"the\" in Berlin", how: "WON (triumphed) + DER (German \"the\")" },
  downer: { clue: "Buzzkill: feathers, hesitation", how: "DOWN (feathers) + ER (hesitation)" },
};
